<a href="https://colab.research.google.com/github/franzmir-oss/tradingmonitor/blob/main/Copia_de_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Mi agente de trading está funcionando 🚀")

Mi agente de trading está funcionando 🚀

In [2]:
!pip install yfinance -q

In [3]:
import yfinance as yf

spy = yf.download("SPY", period="5d", interval="5m")

spy.tail()

/tmp/ipykernel_3676/4080369549.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  spy = yf.download("SPY", period="5d", interval="5m")
[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,SPY,SPY,SPY,SPY,SPY
Datetime,,,,,
2026-08-28 19:35:00+00:00,769.544983,769.575012,769.130005,769.400024,390876
2026-08-28 19:40:00+00:00,769.619995,769.789978,769.530029,769.549988,701568
2026-08-28 19:45:00+00:00,769.239990,769.690002,769.020020,769.599976,802394
2026-08-28 19:50:00+00:00,769.359985,769.780029,769.109985,769.270020,1057313
2026-08-28 19:55:00+00:00,769.380005,769.880005,769.070007,769.349976,2670344

In [4]:
import yfinance as yf
import pandas as pd

# Descargar datos de SPY
spy = yf.download(
    "SPY",
    period="5d",
    interval="5m",
    auto_adjust=False
)

# Quitamos niveles innecesarios de columnas si aparecen
if isinstance(spy.columns, pd.MultiIndex):
    spy.columns = spy.columns.get_level_values(0)

# EMA 9 y EMA 21
spy["EMA_9"] = spy["Close"].ewm(span=9, adjust=False).mean()
spy["EMA_21"] = spy["Close"].ewm(span=21, adjust=False).mean()

# RSI 14
delta = spy["Close"].diff()

ganancias = delta.clip(lower=0)
perdidas = -delta.clip(upper=0)

media_ganancias = ganancias.rolling(14).mean()
media_perdidas = perdidas.rolling(14).mean()

RS = media_ganancias / media_perdidas
spy["RSI_14"] = 100 - (100 / (1 + RS))

# Mostrar los últimos datos
spy[["Close", "EMA_9", "EMA_21", "RSI_14", "Volume"]].tail(10)

[*********************100%***********************]  1 of 1 completed

Price,Close,EMA_9,EMA_21,RSI_14,Volume
Datetime,,,,,
2026-08-28 19:10:00+00:00,769.236328,769.063615,769.246633,45.807930,373847
2026-08-28 19:15:00+00:00,769.210022,769.092897,769.243305,44.643052,298514
2026-08-28 19:20:00+00:00,769.320007,769.138319,769.250278,51.603185,495086
2026-08-28 19:25:00+00:00,769.515015,769.213658,769.274345,51.603185,260564
2026-08-28 19:30:00+00:00,769.400024,769.250931,769.285770,55.709730,395715
2026-08-28 19:35:00+00:00,769.544983,769.309742,769.309335,58.016546,390876
2026-08-28 19:40:00+00:00,769.619995,769.371792,769.337577,54.480420,701568
2026-08-28 19:45:00+00:00,769.239990,769.345432,769.328705,52.233828,802394
2026-08-28 19:50:00+00:00,769.359985,769.348343,769.331549,50.796189,1057313
2026-08-28 19:55:00+00:00,769.380005,769.354675,769.335954,63.260973,2670344

In [5]:
import pandas as pd
import yfinance as yf

# 1. Descarga de datos horarios (60m) para SPY (Enfoque institucional)
print("Descargando datos horarios de SPY...")
spy = yf.download("SPY", period="60d", interval="60m", auto_adjust=False)

# Limpieza de columnas si yfinance devuelve multiíndice
if isinstance(spy.columns, pd.MultiIndex):
  spy.columns = spy.columns.get_level_values(0)

# 2. Cálculo de la SMA 40 (Clave para los pullbacks del Módulo 4 y 5)
spy["SMA_40"] = spy["Close"].rolling(window=40).mean()

# 3. Extraer la hora de la vela para identificar la sesión y la Regla de las 11:00 AM
spy["Hora"] = spy.index.hour

# 4. Mostrar la estructura de los últimos datos con la SMA 40
print("\n--- Últimos registros en Marco Horario (60m) ---")
print(spy[["Close", "SMA_40", "Volume", "Hora"]].tail(12))

Descargando datos horarios de SPY...

[*********************100%***********************]  1 of 1 completed

--- Últimos registros en Marco Horario (60m) ---
Price                           Close      SMA_40    Volume  Hora
Datetime
2026-08-27 15:30:00+00:00  770.909973  765.659380   2969743    15
2026-08-27 16:30:00+00:00  771.750000  765.712379   2858782    16
2026-08-27 17:30:00+00:00  769.460022  765.721629   3207478    17
2026-08-27 18:30:00+00:00  769.940002  765.814630   4031698    18
2026-08-27 19:30:00+00:00  771.039978  765.921880   5493749    19
2026-08-28 13:30:00+00:00  771.299988  766.060754   8479687    13
2026-08-28 14:30:00+00:00  774.950012  766.315004  25412763    14
2026-08-28 15:30:00+00:00  769.599976  766.466003  20395572    15
2026-08-28 16:30:00+00:00  768.820007  766.599254   3734084    16
2026-08-28 17:30:00+00:00  769.059998  766.759753  23768857    17
2026-08-28 18:30:00+00:00  769.515015  766.881378  26916873    18
2026-08-28 19:30:00+00:00  769.380005  766.967003   6018210    19

In [6]:
# 1. Convertir el índice de las velas a la hora oficial de Nueva York
spy.index = spy.index.tz_convert('America/New_York')

# 2. Actualizar la columna de hora con el horario de NY
spy["Hora_NY"] = spy.index.hour

# 3. Aislar estrictamente la vela de las 11:00 AM (Regla de las 11:00 AM)
vela_11am = spy[spy["Hora_NY"] == 11].copy()

# 4. Clasificar si la vela de las 11:00 AM es verde (alcista) o roja (bajista)
vela_11am["Efecto_11AM"] = vela_11am.apply(
    lambda row: 'VERDE 🟢 (Predisposición Alcista)' if row['Close'] > row['Open'] else 'ROJA 🔴 (Predisposición Bajista)',
    axis=1
)

# 5. Mostrar el histórico reciente de la regla de las 11:00 AM
print("--- EVALUACIÓN DE LA REGLA DE LAS 11:00 AM ---")
print(vela_11am[['Open', 'Close', 'Efecto_11AM', 'Volume']].tail(8))

--- EVALUACIÓN DE LA REGLA DE LAS 11:00 AM ---
Price                            Open       Close  \
Datetime
2026-08-19 11:30:00-04:00  771.016296  770.669983
2026-08-20 11:30:00-04:00  766.739990  765.744995
2026-08-21 11:30:00-04:00  765.960022  766.515015
2026-08-24 11:30:00-04:00  763.739990  764.890015
2026-08-25 11:30:00-04:00  765.320007  765.760010
2026-08-26 11:30:00-04:00  765.840027  764.799988
2026-08-27 11:30:00-04:00  770.309998  770.909973
2026-08-28 11:30:00-04:00  774.969971  769.599976

Price                                           Efecto_11AM    Volume
Datetime
2026-08-19 11:30:00-04:00   ROJA 🔴 (Predisposición Bajista)   3117626
2026-08-20 11:30:00-04:00   ROJA 🔴 (Predisposición Bajista)   3494078
2026-08-21 11:30:00-04:00  VERDE 🟢 (Predisposición Alcista)   7924032
2026-08-24 11:30:00-04:00  VERDE 🟢 (Predisposición Alcista)   2992867
2026-08-25 11:30:00-04:00  VERDE 🟢 (Predisposición Alcista)   2818368
2026-08-26 11:30:00-04:00   ROJA 🔴 (Predisposición Bajista)   2611433
2026-08-27 11:30:00-04:00  VERDE 🟢 (Predisposición Alcista)   2969743
2026-08-28 11:30:00-04:00   ROJA 🔴 (Predisposición Bajista)  20395572

In [7]:
# 1. Calcular el bloque completo de Medias Móviles Simples (SMA)
spy["SMA_20"] = spy["Close"].rolling(window=20).mean()
spy["SMA_40"] = spy["Close"].rolling(window=40).mean()
spy["SMA_100"] = spy["Close"].rolling(window=100).mean()
spy["SMA_200"] = spy["Close"].rolling(window=200).mean()

# 2. Definir Alineación en "Líneas de Ferrocarril" Alcista (Módulo 4)
# SMA 20 > SMA 40 > SMA 100 > SMA 200
spy["Tendencia_Alcista"] = (
    (spy["SMA_20"] > spy["SMA_40"]) &
    (spy["SMA_40"] > spy["SMA_100"]) &
    (spy["SMA_100"] > spy["SMA_200"])
)

# 3. Detectar Pullback: cuando el precio toca o se acerca milimétricamente a la SMA 40 (margen del 0.4%)
spy["Distancia_SMA40"] = abs(spy["Low"] - spy["SMA_40"]) / spy["SMA_40"]
spy["Pullback_Alcista_Detectado"] = spy["Tendencia_Alcista"] & (spy["Distancia_SMA40"] <= 0.004)

# 4. Filtrar y mostrar las veces que el sistema ha detectado esta configuración exacta
resultados_pullback = spy[spy["Pullback_Alcista_Detectado"]].copy()

print("--- DETECCIONES DE PULLBACK A LA SMA 40 (TENDENCIA ALCISTA) ---")
if not resultados_pullback.empty:
    print(resultados_pullback[["Close", "SMA_20", "SMA_40", "Volume"]].tail(5))
    print(f"\nTotal de pullbacks alcistas detectados en el histórico cargado: {len(resultados_pullback)}")
else:
    print("No hay coincidencias exactas en este rango de fechas. Vamos a revisar la sensibilidad del rango.")

--- DETECCIONES DE PULLBACK A LA SMA 40 (TENDENCIA ALCISTA) ---
Price                           Close      SMA_20      SMA_40   Volume
Datetime
2026-08-17 11:30:00-04:00  775.289978  776.070258  774.266240  2480472
2026-08-17 12:30:00-04:00  773.580017  776.094757  774.278865  2932105
2026-08-17 13:30:00-04:00  773.590027  776.125259  774.290616  3486505
2026-08-17 14:30:00-04:00  773.119995  776.155258  774.259741  3522124
2026-08-17 15:30:00-04:00  772.679993  775.829758  774.233241  8585280

Total de pullbacks alcistas detectados en el histórico cargado: 31

In [8]:
# 5. GATILLO DE ENTRADA (Confirmación de la Estrategia)
# Identificamos el pullback registrado en la vela anterior
spy["Pullback_Anterior"] = spy["Pullback_Alcista_Detectado"].shift(1)

# Condición de confirmación:
# A) La vela actual es verde sólida (Close > Open)
spy["Vela_Verde"] = spy["Close"] > spy["Open"]

# B) El precio rompe al alza el máximo de la vela de pullback anterior
spy["Ruptura_Maximo"] = spy["High"] > spy["High"].shift(1)

# 6. SEÑAL DEFINITIVA DE COMPRA (CALL)
spy["Señal_CALL"] = spy["Pullback_Anterior"] & spy["Vela_Verde"] & spy["Ruptura_Maximo"]

# Filtrar y mostrar las señales exactas de disparo
entradas_call = spy[spy["Señal_CALL"]].copy()

print("--- SEÑALES EXACTAS DE ENTRADA (CALL) ---")
if not entradas_call.empty:
    print(entradas_call[["Close", "SMA_40", "Volume"]].tail(5))
    print(f"\nTotal de señales de entrada CALL detectadas: {len(entradas_call)}")
else:
    print("No hay señales con la confirmación estricta en este tramo de fechas.")

--- SEÑALES EXACTAS DE ENTRADA (CALL) ---
Price                           Close      SMA_40   Volume
Datetime
2026-08-12 12:30:00-04:00  772.780029  771.711758  2563103
2026-08-12 13:30:00-04:00  773.090027  771.757008  2417715
2026-08-13 09:30:00-04:00  779.190002  771.909486  6564966
2026-08-14 14:30:00-04:00  776.155029  773.920740  3082814

Total de señales de entrada CALL detectadas: 4

In [9]:
# MÓDULO 5: Pullback a la SMA 40 en Tendencia Bajista (PUTs)

# 1. Definir Alineación en "Líneas de Ferrocarril" Bajista
# SMA 20 < SMA 40 < SMA 100 < SMA 200
spy["Tendencia_Bajista"] = (
    (spy["SMA_20"] < spy["SMA_40"]) &
    (spy["SMA_40"] < spy["SMA_100"]) &
    (spy["SMA_100"] < spy["SMA_200"])
)

# 2. Detectar Pullback: cuando el precio rebota y se acerca milimétricamente a la SMA 40 desde abajo
spy["Distancia_SMA40_Bajista"] = abs(spy["High"] - spy["SMA_40"]) / spy["SMA_40"]
spy["Pullback_Bajista_Detectado"] = spy["Tendencia_Bajista"] & (spy["Distancia_SMA40_Bajista"] <= 0.004)

# 3. GATILLO DE ENTRADA (Confirmación Bajista)
# Identificamos el pullback registrado en la vela anterior
spy["Pullback_Bajista_Anterior"] = spy["Pullback_Bajista_Detectado"].shift(1)

# Condición de confirmación para PUT:
# A) La vela actual es roja sólida (Close < Open)
spy["Vela_Roja"] = spy["Close"] < spy["Open"]

# B) El precio rompe a la baja el mínimo de la vela de pullback anterior
spy["Ruptura_Minimo"] = spy["Low"] < spy["Low"].shift(1)

# 4. SEÑAL DEFINITIVA DE COMPRA (PUT)
spy["Señal_PUT"] = spy["Pullback_Bajista_Anterior"] & spy["Vela_Roja"] & spy["Ruptura_Minimo"]

# Filtrar y mostrar las señales exactas de disparo
entradas_put = spy[spy["Señal_PUT"]].copy()

print("--- SEÑALES EXACTAS DE ENTRADA (PUT) ---")
if not entradas_put.empty:
    print(entradas_put[["Close", "SMA_40", "Volume"]].tail(5))
    print(f"\nTotal de señales de entrada PUT detectadas: {len(entradas_put)}")
else:
    print("No hay señales de PUT con la confirmación estricta en este tramo de fechas.")

--- SEÑALES EXACTAS DE ENTRADA (PUT) ---
No hay señales de PUT con la confirmación estricta en este tramo de fechas.

In [10]:
import pandas as pd
import yfinance as yf

# --- SCRIPT MAESTRO DE EVALUACIÓN Y GESTIÓN DE RIESGO ---

# 1. Función de Cálculo Matemático de Contratos y Take Profit (Módulo 6)
# Basado en la fórmula exacta del libro: Duplicar capital neto de comisiones ($7 + $1.25 por contrato)
def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    costo_unitario_real = inversion_neta / num_contratos
    take_profit_limit = costo_unitario_real * 2  # Duplicar el capital invertido
    return costo_unitario_real, take_profit_limit

# 2. Resumen de Señales CALL detectadas y su Plan de Gestión
print("==================================================")
print("     INFORME AUTOMATIZADO - PLAN MAESTRO SPY      ")
print("==================================================")

if 'entradas_call' in locals() and not entradas_call.empty:
    print(f"\n🟢 Se han validado {len(entradas_call)} señales de compra (CALL):\n")
    for fecha, fila in entradas_call.iterrows():
        costo_real, tp = calcular_take_profit()
        print(f"📅 Fecha/Hora: {fecha}")
        print(f"   • Precio SPY: {fila['Close']:.2f} | SMA 40: {fila['SMA_40']:.2f}")
        print(f"   • Volumen institucional: {fila['Volume']:,}")
        print(f"   • 🎯 Configuración Take Profit (Limit Price): ${tp:.3f} por contrato\n")
else:
    print("\n🟢 No hay señales CALL pendientes de ejecución en el filtro actual.")

if 'entradas_put' in locals() and not entradas_put.empty:
    print(f"\n🔴 Se han validado {len(entradas_put)} señales de venta (PUT):\n")
    for fecha, fila in entradas_put.iterrows():
        costo_real, tp = calcular_take_profit()
        print(f"📅 Fecha/Hora: {fecha}")
        print(f"   • Precio SPY: {fila['Close']:.2f} | SMA 40: {fila['SMA_40']:.2f}")
        print(f"   • 🎯 Configuración Take Profit (Limit Price): ${tp:.3f} por contrato\n")
else:
    print("🔴 Sin señales PUT activas en este rango (Mercado en tendencia alcista principal).")

print("==================================================")
print("Sistema sincronizado con la Regla de las 11:00 AM y Módulos 4-6 🚀")

==================================================
     INFORME AUTOMATIZADO - PLAN MAESTRO SPY
==================================================

🟢 Se han validado 4 señales de compra (CALL):

📅 Fecha/Hora: 2026-08-12 12:30:00-04:00
   • Precio SPY: 772.78 | SMA 40: 771.71
   • Volumen institucional: 2,563,103
   • 🎯 Configuración Take Profit (Limit Price): $4.500 por contrato

📅 Fecha/Hora: 2026-08-12 13:30:00-04:00
   • Precio SPY: 773.09 | SMA 40: 771.76
   • Volumen institucional: 2,417,715
   • 🎯 Configuración Take Profit (Limit Price): $4.500 por contrato

📅 Fecha/Hora: 2026-08-13 09:30:00-04:00
   • Precio SPY: 779.19 | SMA 40: 771.91
   • Volumen institucional: 6,564,966
   • 🎯 Configuración Take Profit (Limit Price): $4.500 por contrato

📅 Fecha/Hora: 2026-08-14 14:30:00-04:00
   • Precio SPY: 776.16 | SMA 40: 773.92
   • Volumen institucional: 3,082,814
   • 🎯 Configuración Take Profit (Limit Price): $4.500 por contrato

🔴 Sin señales PUT activas en este rango (Mercado en tendencia alcista principal).
==================================================
Sistema sincronizado con la Regla de las 11:00 AM y Módulos 4-6 🚀

In [11]:
import pandas as pd
import yfinance as yf

# Universo completo de activos, ETFs y empresas de referencia del Plan Maestro
universo_activos = [
    "SPY",
    "QQQ",
    "DIA",  # ETFs Principales e Índices
    "AAPL",
    "AMZN",
    "GOOG",
    "MSFT",
    "NFLX",  # Tecnología y Crecimiento
    "CMG",
    "WMT",
    "COST",
    "MCD",
    "NKE",  # Consumo y Retail
    "JPM",
    "BAC",
    "WFC",
    "C",  # Banca y Finanzas
    "JNJ",
    "KO",
    "PEP",
    "F",  # Salud, Valor e Industriales
]

print(
    "Iniciando escaneo institucional multiactivo para todo el universo del Plan"
    " Maestro...\n"
)

resultados_calls = []
resultados_puts = []


def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
  comision_total = 7.00 + (1.25 * num_contratos)
  inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
  costo_unitario_real = inversion_neta / num_contratos
  return costo_unitario_real * 2  # Duplicar capital neto


for ticker in universo_activos:
  try:
    # Descargar datos horarios en bloque institucional
    df = yf.download(ticker, period="60d", interval="60m", progress=False)
    if df.empty:
      continue

    # Limpieza de columnas si yfinance devuelve multiíndice
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Sincronización horaria a Nueva York
    df.index = df.index.tz_convert("America/New_York")
    df["Hora_NY"] = df.index.hour

    # Bloque de Medias Móviles Simples (SMA)
    df["SMA_20"] = df["Close"].rolling(window=20).mean()
    df["SMA_40"] = df["Close"].rolling(window=40).mean()
    df["SMA_100"] = df["Close"].rolling(window=100).mean()
    df["SMA_200"] = df["Close"].rolling(window=200).mean()

    # --- ESTRATEGIA ALCISTA: Pullback SMA 40 + Ferrocarril (CALL) ---
    tendencia_alcista = (
        (df["SMA_20"] > df["SMA_40"])
        & (df["SMA_40"] > df["SMA_100"])
        & (df["SMA_100"] > df["SMA_200"])
    )
    distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
    pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)

    df["Pull_Anterior"] = pullback_alcista.shift(1)
    df["Vela_Verde"] = df["Close"] > df["Open"]
    df["Ruptura_Max"] = df["High"] > df["High"].shift(1)
    df["Señal_CALL"] = (
        df["Pull_Anterior"] & df["Vela_Verde"] & df["Ruptura_Max"]
    )

    # --- ESTRATEGIA BAJISTA: Pullback SMA 40 + Ferrocarril Invertido (PUT) ---
    tendencia_bajista = (
        (df["SMA_20"] < df["SMA_40"])
        & (df["SMA_40"] < df["SMA_100"])
        & (df["SMA_100"] < df["SMA_200"])
    )
    distancia_bajista = abs(df["High"] - df["SMA_40"]) / df["SMA_40"]
    pullback_bajista = tendencia_bajista & (distancia_bajista <= 0.004)

    df["Pull_Baj_Anterior"] = pullback_bajista.shift(1)
    df["Vela_Roja"] = df["Close"] < df["Open"]
    df["Ruptura_Min"] = df["Low"] < df["Low"].shift(1)
    df["Señal_PUT"] = (
        df["Pull_Baj_Anterior"] & df["Vela_Roja"] & df["Ruptura_Min"]
    )

    # Recolectar señales encontradas
    calls_act = df[df["Señal_CALL"]]
    puts_act = df[df["Señal_PUT"]]

    for idx, row in calls_act.iterrows():
      resultados_calls.append({
          "Ticker": ticker,
          "Fecha": idx,
          "Precio": row["Close"],
          "SMA_40": row["SMA_40"],
          "Volumen": row["Volume"],
          "TP": calcular_take_profit(),
      })

    for idx, row in puts_act.iterrows():
      resultados_puts.append({
          "Ticker": ticker,
          "Fecha": idx,
          "Precio": row["Close"],
          "SMA_40": row["SMA_40"],
          "Volumen": row["Volume"],
          "TP": calcular_take_profit(),
      })

  except Exception as e:
    continue

# --- INFORME GLOBAL DE RESULTADOS ---
print(
    "=========================================================================="
)
print("             ESCANEO GLOBAL MULTIACTIVO - PLAN MAESTRO                    ")
print(
    "=========================================================================="
)

if resultados_calls:
  print(f"\n🟢 TOTAL DE SEÑALES CALL DETECTADAS: {len(resultados_calls)}\n")
  for item in resultados_calls:
    print(
        f"[{item['Ticker']}] 📅 {item['Fecha']} | Precio: {item['Precio']:.2f}"
        f" | SMA 40: {item['SMA_40']:.2f} | Vol: {item['Volumen']:,} | 🎯 TP"
        f" Limit: ${item['TP']:.3f}"
    )
else:
  print("\n🟢 No hay señales CALL activas en este momento para el universo.")

if resultados_puts:
  print(f"\n🔴 TOTAL DE SEÑALES PUT DETECTADAS: {len(resultados_puts)}\n")
  for item in resultados_puts:
    print(
        f"[{item['Ticker']}] 📅 {item['Fecha']} | Precio: {item['Precio']:.2f}"
        f" | SMA 40: {item['SMA_40']:.2f} | Vol: {item['Volumen']:,} | 🎯 TP"
        f" Limit: ${item['TP']:.3f}"
    )
else:
  print("\n🔴 No hay señales PUT activas en este momento para el universo.")

print(
    "\n=========================================================================="
)
print("Análisis completado para todos los activos y ETFs del PDF 🚀")

Iniciando escaneo institucional multiactivo para todo el universo del Plan Maestro...

/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/1137262478.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)

==========================================================================
             ESCANEO GLOBAL MULTIACTIVO - PLAN MAESTRO
==========================================================================

🟢 TOTAL DE SEÑALES CALL DETECTADAS: 81

[SPY] 📅 2026-08-12 12:30:00-04:00 | Precio: 772.78 | SMA 40: 771.71 | Vol: 2,563,103 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-08-12 13:30:00-04:00 | Precio: 773.09 | SMA 40: 771.76 | Vol: 2,417,715 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-08-13 09:30:00-04:00 | Precio: 779.19 | SMA 40: 771.91 | Vol: 6,564,966 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-08-14 14:30:00-04:00 | Precio: 776.16 | SMA 40: 773.92 | Vol: 3,082,814 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-16 15:30:00-04:00 | Precio: 524.78 | SMA 40: 525.04 | Vol: 282,926 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-17 09:30:00-04:00 | Precio: 524.56 | SMA 40: 525.03 | Vol: 2,027,512 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-10 10:30:00-04:00 | Precio: 539.70 | SMA 40: 537.66 | Vol: 359,236 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-10 15:30:00-04:00 | Precio: 539.02 | SMA 40: 539.12 | Vol: 332,359 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-20 13:30:00-04:00 | Precio: 325.94 | SMA 40: 324.77 | Vol: 5,044,844 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-20 14:30:00-04:00 | Precio: 329.02 | SMA 40: 324.99 | Vol: 5,761,535 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-21 11:30:00-04:00 | Precio: 328.62 | SMA 40: 326.06 | Vol: 3,516,853 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-21 14:30:00-04:00 | Precio: 327.93 | SMA 40: 326.89 | Vol: 2,991,406 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-30 15:30:00-04:00 | Precio: 333.85 | SMA 40: 334.41 | Vol: 6,035,542 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-20 11:30:00-04:00 | Precio: 252.48 | SMA 40: 250.11 | Vol: 2,800,714 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-06 15:30:00-04:00 | Precio: 272.20 | SMA 40: 271.00 | Vol: 3,040,548 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-07 09:30:00-04:00 | Precio: 276.15 | SMA 40: 271.93 | Vol: 8,739,038 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-07 10:30:00-04:00 | Precio: 278.19 | SMA 40: 272.94 | Vol: 3,295,121 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-20 11:30:00-04:00 | Precio: 401.49 | SMA 40: 393.41 | Vol: 2,642,229 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-13 09:30:00-04:00 | Precio: 77.17 | SMA 40: 74.46 | Vol: 11,936,147 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-18 10:30:00-04:00 | Precio: 78.75 | SMA 40: 76.23 | Vol: 5,050,815 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-25 10:30:00-04:00 | Precio: 81.64 | SMA 40: 79.67 | Vol: 3,472,320 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-25 14:30:00-04:00 | Precio: 82.21 | SMA 40: 80.25 | Vol: 2,637,867 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-27 14:30:00-04:00 | Precio: 37.21 | SMA 40: 36.95 | Vol: 1,092,808 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-27 15:30:00-04:00 | Precio: 37.23 | SMA 40: 37.01 | Vol: 2,120,924 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-28 09:30:00-04:00 | Precio: 37.88 | SMA 40: 37.08 | Vol: 4,668,817 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-17 15:30:00-04:00 | Precio: 114.33 | SMA 40: 114.27 | Vol: 2,923,416 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-19 09:30:00-04:00 | Precio: 116.57 | SMA 40: 114.97 | Vol: 5,008,120 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-19 13:30:00-04:00 | Precio: 115.86 | SMA 40: 115.27 | Vol: 1,543,569 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-18 10:30:00-04:00 | Precio: 969.23 | SMA 40: 952.46 | Vol: 213,908 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-26 11:30:00-04:00 | Precio: 958.19 | SMA 40: 956.42 | Vol: 77,422 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-26 14:30:00-04:00 | Precio: 959.35 | SMA 40: 955.83 | Vol: 95,640 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-30 14:30:00-04:00 | Precio: 351.60 | SMA 40: 351.87 | Vol: 1,387,575 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-04 10:30:00-04:00 | Precio: 361.10 | SMA 40: 352.73 | Vol: 985,644 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-06 14:30:00-04:00 | Precio: 356.39 | SMA 40: 355.50 | Vol: 335,026 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-07 09:30:00-04:00 | Precio: 356.11 | SMA 40: 355.85 | Vol: 841,174 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-07 11:30:00-04:00 | Precio: 356.92 | SMA 40: 356.12 | Vol: 347,679 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-07 12:30:00-04:00 | Precio: 357.77 | SMA 40: 356.27 | Vol: 260,034 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-07 14:30:00-04:00 | Precio: 358.44 | SMA 40: 356.60 | Vol: 327,987 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-10 09:30:00-04:00 | Precio: 358.24 | SMA 40: 356.81 | Vol: 933,154 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-10 10:30:00-04:00 | Precio: 359.42 | SMA 40: 356.95 | Vol: 521,353 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-10 13:30:00-04:00 | Precio: 358.06 | SMA 40: 357.33 | Vol: 293,647 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-10 14:30:00-04:00 | Precio: 358.39 | SMA 40: 357.42 | Vol: 465,909 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-14 13:30:00-04:00 | Precio: 363.47 | SMA 40: 361.51 | Vol: 405,967 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-17 09:30:00-04:00 | Precio: 363.79 | SMA 40: 362.01 | Vol: 649,653 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-17 11:30:00-04:00 | Precio: 364.86 | SMA 40: 362.35 | Vol: 311,207 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-17 15:30:00-04:00 | Precio: 61.28 | SMA 40: 60.73 | Vol: 7,870,959 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-21 11:30:00-04:00 | Precio: 61.42 | SMA 40: 61.07 | Vol: 4,954,925 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-21 12:30:00-04:00 | Precio: 61.43 | SMA 40: 61.12 | Vol: 2,930,671 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-23 14:30:00-04:00 | Precio: 61.38 | SMA 40: 61.28 | Vol: 2,881,396 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-24 09:30:00-04:00 | Precio: 61.75 | SMA 40: 61.28 | Vol: 5,765,580 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-24 10:30:00-04:00 | Precio: 62.15 | SMA 40: 61.29 | Vol: 5,489,818 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-30 14:30:00-04:00 | Precio: 61.85 | SMA 40: 61.86 | Vol: 1,761,021 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-06 15:30:00-04:00 | Precio: 63.01 | SMA 40: 62.62 | Vol: 3,544,512 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-07 09:30:00-04:00 | Precio: 62.95 | SMA 40: 62.65 | Vol: 4,415,346 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-07 11:30:00-04:00 | Precio: 62.91 | SMA 40: 62.71 | Vol: 1,472,405 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-07 12:30:00-04:00 | Precio: 63.09 | SMA 40: 62.74 | Vol: 1,290,541 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-07 14:30:00-04:00 | Precio: 63.15 | SMA 40: 62.80 | Vol: 1,525,498 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-10 09:30:00-04:00 | Precio: 63.74 | SMA 40: 62.87 | Vol: 4,397,508 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-10 10:30:00-04:00 | Precio: 63.94 | SMA 40: 62.91 | Vol: 2,583,029 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-13 15:30:00-04:00 | Precio: 64.11 | SMA 40: 63.79 | Vol: 3,759,245 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-14 09:30:00-04:00 | Precio: 64.35 | SMA 40: 63.82 | Vol: 2,910,566 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-17 15:30:00-04:00 | Precio: 87.52 | SMA 40: 87.15 | Vol: 3,579,183 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-21 11:30:00-04:00 | Precio: 87.96 | SMA 40: 87.14 | Vol: 1,911,092 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-21 12:30:00-04:00 | Precio: 88.16 | SMA 40: 87.16 | Vol: 1,612,188 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-13 13:30:00-04:00 | Precio: 88.17 | SMA 40: 87.77 | Vol: 1,184,186 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-13 14:30:00-04:00 | Precio: 88.36 | SMA 40: 87.77 | Vol: 928,132 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-14 09:30:00-04:00 | Precio: 88.62 | SMA 40: 87.80 | Vol: 2,019,472 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-14 13:30:00-04:00 | Precio: 88.52 | SMA 40: 87.87 | Vol: 417,719 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-14 14:30:00-04:00 | Precio: 88.54 | SMA 40: 87.91 | Vol: 538,534 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-14 12:30:00-04:00 | Precio: 261.24 | SMA 40: 259.79 | Vol: 174,590 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-17 09:30:00-04:00 | Precio: 262.51 | SMA 40: 260.24 | Vol: 940,195 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-17 15:30:00-04:00 | Precio: 262.45 | SMA 40: 260.91 | Vol: 834,584 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-18 09:30:00-04:00 | Precio: 268.83 | SMA 40: 261.13 | Vol: 1,428,699 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-21 09:30:00-04:00 | Precio: 272.14 | SMA 40: 267.01 | Vol: 1,317,532 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-24 10:30:00-04:00 | Precio: 272.36 | SMA 40: 269.01 | Vol: 721,663 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-24 11:30:00-04:00 | Precio: 273.80 | SMA 40: 269.33 | Vol: 779,470 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-25 10:30:00-04:00 | Precio: 273.47 | SMA 40: 270.94 | Vol: 361,422 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-25 14:30:00-04:00 | Precio: 273.33 | SMA 40: 271.86 | Vol: 288,718 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-25 13:30:00-04:00 | Precio: 142.65 | SMA 40: 142.56 | Vol: 328,527 | 🎯 TP Limit: $4.500
[F] 📅 2026-07-30 14:30:00-04:00 | Precio: 14.80 | SMA 40: 14.72 | Vol: 5,688,011 | 🎯 TP Limit: $4.500
[F] 📅 2026-07-30 15:30:00-04:00 | Precio: 14.88 | SMA 40: 14.74 | Vol: 7,859,486 | 🎯 TP Limit: $4.500

🔴 TOTAL DE SEÑALES PUT DETECTADAS: 30

[QQQ] 📅 2026-07-21 14:30:00-04:00 | Precio: 708.39 | SMA 40: 708.19 | Vol: 2,300,871 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-22 13:30:00-04:00 | Precio: 707.13 | SMA 40: 706.34 | Vol: 1,463,826 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-22 15:30:00-04:00 | Precio: 705.27 | SMA 40: 705.80 | Vol: 2,698,683 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-17 09:30:00-04:00 | Precio: 304.49 | SMA 40: 305.57 | Vol: 7,901,505 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-17 11:30:00-04:00 | Precio: 303.55 | SMA 40: 305.15 | Vol: 2,930,675 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-08-14 10:30:00-04:00 | Precio: 342.95 | SMA 40: 348.49 | Vol: 1,357,795 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-22 11:30:00-04:00 | Precio: 70.08 | SMA 40: 70.51 | Vol: 3,944,758 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-22 12:30:00-04:00 | Precio: 69.52 | SMA 40: 70.40 | Vol: 3,335,271 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-22 13:30:00-04:00 | Precio: 69.10 | SMA 40: 70.29 | Vol: 3,652,920 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-23 14:30:00-04:00 | Precio: 68.76 | SMA 40: 69.26 | Vol: 5,546,162 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-24 09:30:00-04:00 | Precio: 69.12 | SMA 40: 69.02 | Vol: 7,340,702 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-13 12:30:00-04:00 | Precio: 32.71 | SMA 40: 32.80 | Vol: 1,142,622 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-16 13:30:00-04:00 | Precio: 271.46 | SMA 40: 272.16 | Vol: 322,254 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-24 13:30:00-04:00 | Precio: 264.69 | SMA 40: 265.58 | Vol: 290,065 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-24 14:30:00-04:00 | Precio: 264.40 | SMA 40: 265.36 | Vol: 321,719 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-07-27 13:30:00-04:00 | Precio: 42.01 | SMA 40: 42.19 | Vol: 1,323,594 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-05 11:30:00-04:00 | Precio: 41.69 | SMA 40: 42.13 | Vol: 1,496,563 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-10 13:30:00-04:00 | Precio: 41.86 | SMA 40: 41.96 | Vol: 971,902 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-14 09:30:00-04:00 | Precio: 40.97 | SMA 40: 41.37 | Vol: 3,378,179 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-18 15:30:00-04:00 | Precio: 40.06 | SMA 40: 40.49 | Vol: 3,743,122 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-28 13:30:00-04:00 | Precio: 131.69 | SMA 40: 132.37 | Vol: 452,646 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-29 09:30:00-04:00 | Precio: 128.93 | SMA 40: 132.26 | Vol: 2,016,853 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-07-22 14:30:00-04:00 | Precio: 135.45 | SMA 40: 136.31 | Vol: 653,008 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-07-23 09:30:00-04:00 | Precio: 133.88 | SMA 40: 136.23 | Vol: 1,153,244 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-10 13:30:00-04:00 | Precio: 137.58 | SMA 40: 138.54 | Vol: 411,477 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-10 14:30:00-04:00 | Precio: 137.29 | SMA 40: 138.48 | Vol: 545,161 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-11 10:30:00-04:00 | Precio: 137.05 | SMA 40: 138.35 | Vol: 643,489 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-12 09:30:00-04:00 | Precio: 137.01 | SMA 40: 138.18 | Vol: 1,234,748 | 🎯 TP Limit: $4.500
[F] 📅 2026-08-27 15:30:00-04:00 | Precio: 13.97 | SMA 40: 14.02 | Vol: 3,421,487 | 🎯 TP Limit: $4.500
[F] 📅 2026-08-28 09:30:00-04:00 | Precio: 13.88 | SMA 40: 14.02 | Vol: 17,131,089 | 🎯 TP Limit: $4.500

==========================================================================
Análisis completado para todos los activos y ETFs del PDF 🚀

In [12]:
import pandas as pd
import yfinance as yf

universo_activos = [
    "SPY", "QQQ", "DIA",
    "AAPL", "AMZN", "GOOG", "MSFT", "NFLX",
    "CMG", "WMT", "COST", "MCD", "NKE",
    "JPM", "BAC", "WFC", "C",
    "JNJ", "KO", "PEP", "F"
]

print("Iniciando escaneo avanzado: Añadiendo Estrategia 5 (Caída + Hammer + Ruptura)...\n")

resultados_estrategia_5 = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # 1. Detectar caída previa pronunciada (mínimo de los últimos 5 periodos menor al promedio)
        df["Caida_Previa"] = df["Close"] < df["Close"].shift(5)

        # 2. Identificar patrón Vela Hammer (Martillo)
        cuerpo = abs(df["Close"] - df["Open"])
        rango_total = df["High"] - df["Low"]
        sombra_inferior = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_superior = df["High"] - df[["Open", "Close"]].max(axis=1)

        # El cuerpo es pequeño, la sombra inferior es al menos el doble del cuerpo, y la superior es mínima
        df["Es_Hammer"] = (
            (cuerpo > 0) &
            (sombra_inferior >= (2 * cuerpo)) &
            (sombra_superior <= (0.5 * cuerpo)) &
            (rango_total > 0)
        )

        # 3. Gatillo: Ruptura alcista del máximo de la vela Hammer en la vela siguiente
        df["Hammer_Anterior"] = df["Es_Hammer"].shift(1)
        df["Ruptura_Hammer"] = df["High"] > df["High"].shift(1)
        df["Señal_Hammer_CALL"] = df["Caida_Previa"] & df["Hammer_Anterior"] & df["Ruptura_Hammer"]

        # Filtrar aciertos
        senales = df[df["Señal_Hammer_CALL"]]
        for idx, row in senales.iterrows():
            resultados_estrategia_5.append({
                "Ticker": ticker,
                "Fecha": idx,
                "Precio": row["Close"],
                "Volumen": row["Volume"],
                "TP": calcular_take_profit()
            })

    except Exception as e:
        continue

print("==========================================================================")
print("       RESULTADOS: ESTRATEGIA 5 (CAÍDA + HAMMER + RUPTURA CALL)           ")
print("==========================================================================")

if resultados_estrategia_5:
    print(f"\n🟢 TOTAL DE SEÑALES HAMMER DETECTADAS: {len(resultados_estrategia_5)}\n")
    for item in resultados_estrategia_5:
        print(f"[{item['Ticker']}] 📅 {item['Fecha']} | Precio: {item['Precio']:.2f} | Vol: {item['Volumen']:,} | 🎯 TP Limit: ${item['TP']:.3f}")
else:
    print("\n🟢 No hay patrones Hammer con ruptura en este tramo de fechas.")
print("==========================================================================")

Iniciando escaneo avanzado: Añadiendo Estrategia 5 (Caída + Hammer + Ruptura)...

/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/2619868369.py:23: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)

==========================================================================
       RESULTADOS: ESTRATEGIA 5 (CAÍDA + HAMMER + RUPTURA CALL)
==========================================================================

🟢 TOTAL DE SEÑALES HAMMER DETECTADAS: 80

[SPY] 📅 2026-06-05 13:30:00-04:00 | Precio: 740.90 | Vol: 10,285,858 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-06-17 13:30:00-04:00 | Precio: 728.69 | Vol: 7,474,427 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-01 11:30:00-04:00 | Precio: 729.23 | Vol: 4,110,781 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-02 14:30:00-04:00 | Precio: 709.85 | Vol: 4,366,032 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-08 14:30:00-04:00 | Precio: 508.93 | Vol: 456,689 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-26 11:30:00-04:00 | Precio: 518.90 | Vol: 403,840 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-07 14:30:00-04:00 | Precio: 527.84 | Vol: 267,546 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-20 11:30:00-04:00 | Precio: 519.80 | Vol: 128,178 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-22 09:30:00-04:00 | Precio: 522.39 | Vol: 1,287,492 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-17 14:30:00-04:00 | Precio: 534.30 | Vol: 220,819 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-06-09 14:30:00-04:00 | Precio: 291.13 | Vol: 5,060,332 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-20 13:30:00-04:00 | Precio: 325.94 | Vol: 5,044,844 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-20 09:30:00-04:00 | Precio: 316.47 | Vol: 7,715,714 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-06-04 14:30:00-04:00 | Precio: 253.79 | Vol: 3,018,818 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-23 12:30:00-04:00 | Precio: 234.49 | Vol: 3,069,226 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-04 12:30:00-04:00 | Precio: 278.75 | Vol: 5,155,514 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-16 09:30:00-04:00 | Precio: 368.43 | Vol: 2,360,795 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-17 13:30:00-04:00 | Precio: 363.70 | Vol: 1,786,545 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-30 15:30:00-04:00 | Precio: 353.32 | Vol: 3,932,413 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-09 12:30:00-04:00 | Precio: 352.54 | Vol: 859,265 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-08-12 12:30:00-04:00 | Precio: 341.67 | Vol: 1,201,019 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-06-17 13:30:00-04:00 | Precio: 383.02 | Vol: 3,431,106 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-14 12:30:00-04:00 | Precio: 386.74 | Vol: 1,965,763 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-08-18 09:30:00-04:00 | Precio: 481.15 | Vol: 4,719,078 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-24 13:30:00-04:00 | Precio: 72.71 | Vol: 5,247,602 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-30 11:30:00-04:00 | Precio: 72.91 | Vol: 3,169,563 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-31 13:30:00-04:00 | Precio: 71.66 | Vol: 2,840,274 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-20 11:30:00-04:00 | Precio: 80.33 | Vol: 1,669,680 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-04 15:30:00-04:00 | Precio: 33.82 | Vol: 7,334,316 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-28 15:30:00-04:00 | Precio: 38.03 | Vol: 2,176,651 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-06-15 10:30:00-04:00 | Precio: 120.19 | Vol: 1,284,209 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-07-09 11:30:00-04:00 | Precio: 111.83 | Vol: 1,620,070 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-08 14:30:00-04:00 | Precio: 974.65 | Vol: 131,584 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-11 13:30:00-04:00 | Precio: 978.16 | Vol: 181,564 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-25 11:30:00-04:00 | Precio: 943.40 | Vol: 180,181 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-14 15:30:00-04:00 | Precio: 921.74 | Vol: 225,094 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-20 11:30:00-04:00 | Precio: 940.49 | Vol: 132,078 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-06-04 14:30:00-04:00 | Precio: 273.15 | Vol: 301,698 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-07 14:30:00-04:00 | Precio: 282.44 | Vol: 255,787 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-15 10:30:00-04:00 | Precio: 268.45 | Vol: 517,457 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-21 12:30:00-04:00 | Precio: 265.17 | Vol: 231,961 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-05 15:30:00-04:00 | Precio: 273.95 | Vol: 800,870 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-17 12:30:00-04:00 | Precio: 266.78 | Vol: 240,221 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-25 15:30:00-04:00 | Precio: 40.94 | Vol: 3,837,971 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-30 10:30:00-04:00 | Precio: 41.15 | Vol: 5,024,447 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-07-23 14:30:00-04:00 | Precio: 40.92 | Vol: 1,629,162 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-21 14:30:00-04:00 | Precio: 40.67 | Vol: 1,048,384 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-14 14:30:00-04:00 | Precio: 341.67 | Vol: 811,207 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-16 12:30:00-04:00 | Precio: 345.29 | Vol: 620,650 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-12 14:30:00-04:00 | Precio: 365.42 | Vol: 374,075 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-05 09:30:00-04:00 | Precio: 53.90 | Vol: 7,227,202 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-26 09:30:00-04:00 | Precio: 57.90 | Vol: 6,882,092 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-26 11:30:00-04:00 | Precio: 57.96 | Vol: 2,932,526 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-14 14:30:00-04:00 | Precio: 60.60 | Vol: 4,247,601 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-07 14:30:00-04:00 | Precio: 87.11 | Vol: 774,713 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-22 09:30:00-04:00 | Precio: 86.68 | Vol: 1,688,187 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-23 10:30:00-04:00 | Precio: 85.81 | Vol: 1,068,606 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-14 14:30:00-04:00 | Precio: 88.54 | Vol: 538,534 | 🎯 TP Limit: $4.500
[C] 📅 2026-06-30 12:30:00-04:00 | Precio: 140.44 | Vol: 861,809 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-01 09:30:00-04:00 | Precio: 139.81 | Vol: 2,873,051 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-22 09:30:00-04:00 | Precio: 132.60 | Vol: 2,016,818 | 🎯 TP Limit: $4.500
[C] 📅 2026-08-07 10:30:00-04:00 | Precio: 134.59 | Vol: 545,945 | 🎯 TP Limit: $4.500
[C] 📅 2026-08-12 14:30:00-04:00 | Precio: 137.83 | Vol: 550,604 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-06-16 09:30:00-04:00 | Precio: 233.88 | Vol: 1,436,259 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-06-24 14:30:00-04:00 | Precio: 240.74 | Vol: 658,714 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-07-07 14:30:00-04:00 | Precio: 267.30 | Vol: 730,085 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-07-09 12:30:00-04:00 | Precio: 259.64 | Vol: 545,872 | 🎯 TP Limit: $4.500
[JNJ] 📅 2026-08-06 12:30:00-04:00 | Precio: 255.88 | Vol: 308,858 | 🎯 TP Limit: $4.500
[KO] 📅 2026-07-15 10:30:00-04:00 | Precio: 82.95 | Vol: 1,634,229 | 🎯 TP Limit: $4.500
[KO] 📅 2026-08-03 11:30:00-04:00 | Precio: 86.80 | Vol: 928,191 | 🎯 TP Limit: $4.500
[KO] 📅 2026-08-06 12:30:00-04:00 | Precio: 86.48 | Vol: 753,368 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-07-09 10:30:00-04:00 | Precio: 137.46 | Vol: 2,047,233 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-07-10 13:30:00-04:00 | Precio: 137.15 | Vol: 1,052,518 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-04 13:30:00-04:00 | Precio: 138.55 | Vol: 552,690 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-13 14:30:00-04:00 | Precio: 140.16 | Vol: 526,253 | 🎯 TP Limit: $4.500
[PEP] 📅 2026-08-26 11:30:00-04:00 | Precio: 142.38 | Vol: 369,309 | 🎯 TP Limit: $4.500
[F] 📅 2026-06-09 13:30:00-04:00 | Precio: 14.82 | Vol: 5,245,388 | 🎯 TP Limit: $4.500
[F] 📅 2026-07-28 15:30:00-04:00 | Precio: 14.96 | Vol: 10,851,732 | 🎯 TP Limit: $4.500
[F] 📅 2026-08-24 13:30:00-04:00 | Precio: 13.94 | Vol: 5,282,519 | 🎯 TP Limit: $4.500
[F] 📅 2026-08-26 11:30:00-04:00 | Precio: 13.84 | Vol: 2,929,741 | 🎯 TP Limit: $4.500
==========================================================================

In [13]:
import pandas as pd
import yfinance as yf

universo_activos = [
    "SPY", "QQQ", "DIA",
    "AAPL", "AMZN", "GOOG", "MSFT", "NFLX",
    "CMG", "WMT", "COST", "MCD", "NKE",
    "JPM", "BAC", "WFC", "C",
    "JNJ", "KO", "PEP", "F"
]

print("==========================================================================")
print("     ESCANEO MULTIACTIVO: ESTRATEGIA 1 & ESTRATEGIA 2 - PLAN MAESTRO      ")
print("==========================================================================")

resultados_est1 = []
resultados_est2 = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # --- ESTRATEGIA 1: Ruptura de línea bajista sobre piso fuerte (Máxima Rentabilidad) ---
        df["Soporte_Fuerte"] = df["Low"].rolling(window=20).min()
        df["Max_Decreciente"] = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        df["Cerca_Soporte"] = (df["Low"] <= df["Soporte_Fuerte"] * 1.01)

        # Gatillo Estrategia 1
        df["Señal_Est_1"] = df["Max_Decreciente"] & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        # --- ESTRATEGIA 2: Ruptura de Rango / Máximo con Volumen Institucional ---
        df["Max_20"] = df["High"].rolling(window=20).max().shift(1)
        df["Volumen_Alto"] = df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)
        df["Señal_Est_2"] = (df["Close"] > df["Max_20"]) & df["Volumen_Alto"] & (df["Close"] > df["Open"])

        # Recolectar Estrategia 1
        est1_act = df[df["Señal_Est_1"]]
        for idx, row in est1_act.iterrows():
            resultados_est1.append({
                "Ticker": ticker, "Fecha": idx, "Precio": row["Close"],
                "Volumen": row["Volume"], "TP": calcular_take_profit()
            })

        # Recolectar Estrategia 2
        est2_act = df[df["Señal_Est_2"]]
        for idx, row in est2_act.iterrows():
            resultados_est2.append({
                "Ticker": ticker, "Fecha": idx, "Precio": row["Close"],
                "Volumen": row["Volume"], "TP": calcular_take_profit()
            })

    except Exception as e:
        continue

# --- REPORTES ---
print("\n--- [ESTRATEGIA 1] Ruptura sobre Piso Fuerte (Máxima Rentabilidad) ---")
if resultados_est1:
    print(f"Total señales Estrategia 1 detectadas: {len(resultados_est1)}\n")
    for item in resultados_est1:
        print(f"[{item['Ticker']}] 📅 {item['Fecha']} | Precio: {item['Precio']:.2f} | Vol: {item['Volumen']:,} | 🎯 TP Limit: ${item['TP']:.3f}")
else:
    print("No hay señales activas para la Estrategia 1 en este tramo.")

print("\n--- [ESTRATEGIA 2] Ruptura de Rango con Volumen Institucional ---")
if resultados_est2:
    print(f"Total señales Estrategia 2 detectadas: {len(resultados_est2)}\n")
    for item in resultados_est2:
        print(f"[{item['Ticker']}] 📅 {item['Fecha']} | Precio: {item['Precio']:.2f} | Vol: {item['Volumen']:,} | 🎯 TP Limit: ${item['TP']:.3f}")
else:
    print("No hay señales activas para la Estrategia 2 en este tramo.")

print("\n==========================================================================")
print("Escaneo de Estrategia 1 y Estrategia 2 completado 🚀")

==========================================================================
     ESCANEO MULTIACTIVO: ESTRATEGIA 1 & ESTRATEGIA 2 - PLAN MAESTRO
==========================================================================

/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)
/tmp/ipykernel_3676/4136815385.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, period="60d", interval="60m", progress=False)

--- [ESTRATEGIA 1] Ruptura sobre Piso Fuerte (Máxima Rentabilidad) ---
Total señales Estrategia 1 detectadas: 284

[SPY] 📅 2026-06-11 09:30:00-04:00 | Precio: 728.82 | Vol: 13,356,726 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-06-17 09:30:00-04:00 | Precio: 751.69 | Vol: 8,522,283 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-06-18 15:30:00-04:00 | Precio: 746.59 | Vol: 11,540,450 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-06-24 09:30:00-04:00 | Precio: 736.49 | Vol: 9,730,442 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-06-26 09:30:00-04:00 | Precio: 733.49 | Vol: 9,853,564 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-07-02 09:30:00-04:00 | Precio: 747.94 | Vol: 8,848,490 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-07-15 09:30:00-04:00 | Precio: 754.62 | Vol: 8,400,817 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-07-16 15:30:00-04:00 | Precio: 750.76 | Vol: 11,103,382 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-07-17 11:30:00-04:00 | Precio: 745.94 | Vol: 7,361,998 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-07-23 15:30:00-04:00 | Precio: 738.17 | Vol: 11,577,395 | 🎯 TP Limit: $4.500
[SPY] 📅 2026-08-27 15:30:00-04:00 | Precio: 771.04 | Vol: 5,493,749 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-06-11 09:30:00-04:00 | Precio: 702.12 | Vol: 14,568,531 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-06-15 09:30:00-04:00 | Precio: 740.99 | Vol: 12,270,724 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-06-24 09:30:00-04:00 | Precio: 715.15 | Vol: 9,967,443 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-08 09:30:00-04:00 | Precio: 707.20 | Vol: 10,665,098 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-10 09:30:00-04:00 | Precio: 722.45 | Vol: 6,824,794 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-07-23 15:30:00-04:00 | Precio: 691.80 | Vol: 4,708,242 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-08-04 09:30:00-04:00 | Precio: 716.01 | Vol: 12,424,976 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-08-07 09:30:00-04:00 | Precio: 721.25 | Vol: 9,053,853 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-08-11 15:30:00-04:00 | Precio: 718.34 | Vol: 3,980,481 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-08-18 12:30:00-04:00 | Precio: 718.35 | Vol: 4,517,225 | 🎯 TP Limit: $4.500
[QQQ] 📅 2026-08-27 15:30:00-04:00 | Precio: 721.06 | Vol: 4,182,410 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-09 12:30:00-04:00 | Precio: 506.70 | Vol: 988,383 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-11 09:30:00-04:00 | Precio: 503.28 | Vol: 1,724,710 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-16 09:30:00-04:00 | Precio: 521.24 | Vol: 1,683,696 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-17 09:30:00-04:00 | Precio: 523.68 | Vol: 1,795,004 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-23 09:30:00-04:00 | Precio: 517.77 | Vol: 1,408,721 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-26 09:30:00-04:00 | Precio: 519.82 | Vol: 1,259,388 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-06-29 09:30:00-04:00 | Precio: 521.67 | Vol: 1,839,463 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-01 09:30:00-04:00 | Precio: 523.30 | Vol: 825,378 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-02 09:30:00-04:00 | Precio: 525.67 | Vol: 840,259 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-09 09:30:00-04:00 | Precio: 523.87 | Vol: 632,429 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-21 09:30:00-04:00 | Precio: 521.12 | Vol: 1,035,523 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-22 09:30:00-04:00 | Precio: 522.39 | Vol: 1,287,492 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-07-23 14:30:00-04:00 | Precio: 516.27 | Vol: 573,623 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-05 09:30:00-04:00 | Precio: 545.93 | Vol: 1,831,536 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-07 09:30:00-04:00 | Precio: 540.19 | Vol: 751,996 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-17 11:30:00-04:00 | Precio: 535.36 | Vol: 304,665 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-21 09:30:00-04:00 | Precio: 530.78 | Vol: 693,096 | 🎯 TP Limit: $4.500
[DIA] 📅 2026-08-27 15:30:00-04:00 | Precio: 535.17 | Vol: 294,648 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-06-18 09:30:00-04:00 | Precio: 299.61 | Vol: 26,189,695 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-06-23 09:30:00-04:00 | Precio: 300.51 | Vol: 9,260,481 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-06-25 13:30:00-04:00 | Precio: 279.35 | Vol: 8,443,492 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-06-30 15:30:00-04:00 | Precio: 289.09 | Vol: 8,374,915 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-24 14:30:00-04:00 | Precio: 332.49 | Vol: 6,248,052 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-07-28 15:30:00-04:00 | Precio: 340.16 | Vol: 6,415,578 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-04 09:30:00-04:00 | Precio: 306.81 | Vol: 16,371,244 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-12 15:30:00-04:00 | Precio: 302.23 | Vol: 5,484,225 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-19 14:30:00-04:00 | Precio: 316.68 | Vol: 5,086,965 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-26 14:30:00-04:00 | Precio: 314.84 | Vol: 3,850,044 | 🎯 TP Limit: $4.500
[AAPL] 📅 2026-08-27 15:30:00-04:00 | Precio: 314.58 | Vol: 3,310,734 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-06-09 12:30:00-04:00 | Precio: 243.51 | Vol: 5,901,758 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-06-26 15:30:00-04:00 | Precio: 230.55 | Vol: 18,647,634 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-02 09:30:00-04:00 | Precio: 244.07 | Vol: 7,849,573 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-20 09:30:00-04:00 | Precio: 249.45 | Vol: 5,797,092 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-22 14:30:00-04:00 | Precio: 244.59 | Vol: 4,137,260 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-23 11:30:00-04:00 | Precio: 234.80 | Vol: 5,750,929 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-23 15:30:00-04:00 | Precio: 233.56 | Vol: 5,636,231 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-07-30 14:30:00-04:00 | Precio: 239.52 | Vol: 8,409,950 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-10 15:30:00-04:00 | Precio: 278.08 | Vol: 4,718,385 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-19 09:30:00-04:00 | Precio: 261.17 | Vol: 7,142,748 | 🎯 TP Limit: $4.500
[AMZN] 📅 2026-08-27 15:30:00-04:00 | Precio: 256.22 | Vol: 3,908,787 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-15 09:30:00-04:00 | Precio: 367.00 | Vol: 3,945,692 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-16 09:30:00-04:00 | Precio: 368.43 | Vol: 2,360,795 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-17 13:30:00-04:00 | Precio: 363.70 | Vol: 1,786,545 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-22 12:30:00-04:00 | Precio: 346.32 | Vol: 2,841,219 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-06-26 14:30:00-04:00 | Precio: 341.12 | Vol: 3,447,044 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-08 15:30:00-04:00 | Precio: 358.60 | Vol: 1,939,257 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-14 09:30:00-04:00 | Precio: 353.77 | Vol: 2,098,281 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-16 09:30:00-04:00 | Precio: 372.24 | Vol: 3,619,164 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-23 11:30:00-04:00 | Precio: 320.97 | Vol: 4,601,336 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-07-24 09:30:00-04:00 | Precio: 319.87 | Vol: 5,941,981 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-08-13 15:30:00-04:00 | Precio: 343.98 | Vol: 2,309,555 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-08-19 10:30:00-04:00 | Precio: 342.07 | Vol: 1,920,573 | 🎯 TP Limit: $4.500
[GOOG] 📅 2026-08-27 15:30:00-04:00 | Precio: 337.55 | Vol: 1,475,633 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-06-11 13:30:00-04:00 | Precio: 388.81 | Vol: 5,214,507 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-06-23 09:30:00-04:00 | Precio: 376.28 | Vol: 9,878,894 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-06-25 13:30:00-04:00 | Precio: 357.72 | Vol: 7,853,978 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-02 09:30:00-04:00 | Precio: 388.65 | Vol: 7,748,355 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-15 09:30:00-04:00 | Precio: 395.04 | Vol: 7,982,499 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-28 09:30:00-04:00 | Precio: 395.52 | Vol: 9,088,311 | 🎯 TP Limit: $4.500
[MSFT] 📅 2026-07-31 09:30:00-04:00 | Precio: 453.32 | Vol: 15,052,306 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-16 14:30:00-04:00 | Precio: 78.50 | Vol: 6,687,900 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-18 09:30:00-04:00 | Precio: 77.11 | Vol: 13,012,389 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-22 13:30:00-04:00 | Precio: 73.18 | Vol: 9,260,092 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-06-29 09:30:00-04:00 | Precio: 75.66 | Vol: 11,572,893 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-01 09:30:00-04:00 | Precio: 73.12 | Vol: 10,311,878 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-10 13:30:00-04:00 | Precio: 73.38 | Vol: 4,616,439 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-15 09:30:00-04:00 | Precio: 74.74 | Vol: 7,227,636 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-07-28 09:30:00-04:00 | Precio: 73.57 | Vol: 12,781,009 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-11 15:30:00-04:00 | Precio: 74.78 | Vol: 3,429,803 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-13 12:30:00-04:00 | Precio: 77.20 | Vol: 3,375,176 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-17 15:30:00-04:00 | Precio: 76.03 | Vol: 4,216,998 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-19 09:30:00-04:00 | Precio: 80.22 | Vol: 8,329,455 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-20 09:30:00-04:00 | Precio: 80.28 | Vol: 5,704,591 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-24 09:30:00-04:00 | Precio: 80.31 | Vol: 4,671,581 | 🎯 TP Limit: $4.500
[NFLX] 📅 2026-08-25 09:30:00-04:00 | Precio: 81.57 | Vol: 5,468,211 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-09 15:30:00-04:00 | Precio: 29.88 | Vol: 3,332,793 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-15 15:30:00-04:00 | Precio: 32.73 | Vol: 3,020,367 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-18 09:30:00-04:00 | Precio: 32.56 | Vol: 3,583,107 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-23 09:30:00-04:00 | Precio: 31.27 | Vol: 2,979,078 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-25 14:30:00-04:00 | Precio: 32.15 | Vol: 2,523,046 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-06-26 14:30:00-04:00 | Precio: 33.15 | Vol: 2,260,069 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-07-17 09:30:00-04:00 | Precio: 35.32 | Vol: 5,335,020 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-07-17 14:30:00-04:00 | Precio: 34.56 | Vol: 2,313,846 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-07-20 11:30:00-04:00 | Precio: 33.12 | Vol: 2,625,462 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-07-27 09:30:00-04:00 | Precio: 32.96 | Vol: 3,337,905 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-07-30 09:30:00-04:00 | Precio: 38.06 | Vol: 13,170,117 | 🎯 TP Limit: $4.500
[CMG] 📅 2026-08-19 09:30:00-04:00 | Precio: 35.07 | Vol: 3,999,059 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-06-16 15:30:00-04:00 | Precio: 121.02 | Vol: 3,854,661 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-06-17 15:30:00-04:00 | Precio: 118.16 | Vol: 3,271,956 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-07-01 11:30:00-04:00 | Precio: 108.16 | Vol: 3,679,293 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-07-15 09:30:00-04:00 | Precio: 113.91 | Vol: 2,144,405 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-07-16 09:30:00-04:00 | Precio: 113.96 | Vol: 3,703,335 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-05 15:30:00-04:00 | Precio: 112.35 | Vol: 3,330,116 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-17 15:30:00-04:00 | Precio: 114.33 | Vol: 2,923,416 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-20 11:30:00-04:00 | Precio: 103.94 | Vol: 8,249,661 | 🎯 TP Limit: $4.500
[WMT] 📅 2026-08-20 15:30:00-04:00 | Precio: 103.83 | Vol: 9,758,083 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-16 09:30:00-04:00 | Precio: 988.15 | Vol: 247,133 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-16 15:30:00-04:00 | Precio: 986.61 | Vol: 211,831 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-17 15:30:00-04:00 | Precio: 965.60 | Vol: 236,691 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-18 15:30:00-04:00 | Precio: 951.11 | Vol: 298,821 | 🎯 TP Limit: $4.500
[COST] 📅 2026-06-22 15:30:00-04:00 | Precio: 950.98 | Vol: 293,846 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-09 12:30:00-04:00 | Precio: 913.47 | Vol: 314,613 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-14 15:30:00-04:00 | Precio: 921.74 | Vol: 225,094 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-16 09:30:00-04:00 | Precio: 928.22 | Vol: 387,301 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-20 15:30:00-04:00 | Precio: 935.78 | Vol: 263,242 | 🎯 TP Limit: $4.500
[COST] 📅 2026-07-29 15:30:00-04:00 | Precio: 973.72 | Vol: 332,195 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-04 11:30:00-04:00 | Precio: 943.58 | Vol: 208,925 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-05 15:30:00-04:00 | Precio: 942.02 | Vol: 281,741 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-06 15:30:00-04:00 | Precio: 949.19 | Vol: 206,217 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-12 15:30:00-04:00 | Precio: 949.68 | Vol: 188,763 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-19 09:30:00-04:00 | Precio: 974.35 | Vol: 347,069 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-20 15:30:00-04:00 | Precio: 933.46 | Vol: 355,661 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-21 15:30:00-04:00 | Precio: 947.56 | Vol: 288,826 | 🎯 TP Limit: $4.500
[COST] 📅 2026-08-28 09:30:00-04:00 | Precio: 946.57 | Vol: 336,810 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-06-09 09:30:00-04:00 | Precio: 280.86 | Vol: 727,828 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-06-16 09:30:00-04:00 | Precio: 288.05 | Vol: 1,155,662 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-06-16 15:30:00-04:00 | Precio: 287.94 | Vol: 448,281 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-06-17 14:30:00-04:00 | Precio: 284.06 | Vol: 572,882 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-16 09:30:00-04:00 | Precio: 268.24 | Vol: 948,641 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-23 14:30:00-04:00 | Precio: 262.24 | Vol: 524,306 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-07-24 15:30:00-04:00 | Precio: 264.76 | Vol: 543,242 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-03 13:30:00-04:00 | Precio: 268.63 | Vol: 756,271 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-05 15:30:00-04:00 | Precio: 273.95 | Vol: 800,870 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-18 09:30:00-04:00 | Precio: 267.52 | Vol: 688,629 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-19 09:30:00-04:00 | Precio: 270.45 | Vol: 1,019,774 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-20 09:30:00-04:00 | Precio: 269.07 | Vol: 775,423 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-24 15:30:00-04:00 | Precio: 272.54 | Vol: 511,743 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-26 14:30:00-04:00 | Precio: 267.57 | Vol: 567,276 | 🎯 TP Limit: $4.500
[MCD] 📅 2026-08-28 09:30:00-04:00 | Precio: 263.60 | Vol: 900,910 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-15 09:30:00-04:00 | Precio: 45.56 | Vol: 3,394,294 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-15 15:30:00-04:00 | Precio: 45.22 | Vol: 2,160,940 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-17 09:30:00-04:00 | Precio: 45.30 | Vol: 2,310,317 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-18 09:30:00-04:00 | Precio: 45.17 | Vol: 4,621,524 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-23 11:30:00-04:00 | Precio: 42.76 | Vol: 3,690,726 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-06-25 15:30:00-04:00 | Precio: 40.94 | Vol: 3,837,971 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-07-01 09:30:00-04:00 | Precio: 42.28 | Vol: 30,851,477 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-07-15 09:30:00-04:00 | Precio: 43.35 | Vol: 3,368,554 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-04 15:30:00-04:00 | Precio: 41.51 | Vol: 3,885,197 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-13 09:30:00-04:00 | Precio: 40.74 | Vol: 5,882,604 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-17 14:30:00-04:00 | Precio: 39.26 | Vol: 6,854,766 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-19 09:30:00-04:00 | Precio: 41.12 | Vol: 6,657,132 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-24 13:30:00-04:00 | Precio: 41.03 | Vol: 2,275,247 | 🎯 TP Limit: $4.500
[NKE] 📅 2026-08-25 15:30:00-04:00 | Precio: 39.47 | Vol: 5,083,496 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-06-11 09:30:00-04:00 | Precio: 311.29 | Vol: 1,204,551 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-06-16 09:30:00-04:00 | Precio: 327.38 | Vol: 1,923,134 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-06-16 15:30:00-04:00 | Precio: 331.18 | Vol: 1,151,230 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-06-29 09:30:00-04:00 | Precio: 330.67 | Vol: 1,326,119 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-01 09:30:00-04:00 | Precio: 330.72 | Vol: 1,142,062 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-01 15:30:00-04:00 | Precio: 334.08 | Vol: 1,139,071 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-09 09:30:00-04:00 | Precio: 334.67 | Vol: 1,514,314 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-17 09:30:00-04:00 | Precio: 343.92 | Vol: 2,318,122 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-21 09:30:00-04:00 | Precio: 342.83 | Vol: 1,058,582 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-22 09:30:00-04:00 | Precio: 346.38 | Vol: 1,184,529 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-22 15:30:00-04:00 | Precio: 348.37 | Vol: 861,773 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-24 15:30:00-04:00 | Precio: 353.16 | Vol: 886,777 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-07-30 09:30:00-04:00 | Precio: 348.58 | Vol: 1,184,125 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-03 09:30:00-04:00 | Precio: 354.72 | Vol: 932,651 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-03 15:30:00-04:00 | Precio: 352.61 | Vol: 921,170 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-05 09:30:00-04:00 | Precio: 361.34 | Vol: 983,403 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-14 09:30:00-04:00 | Precio: 365.24 | Vol: 677,004 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-19 15:30:00-04:00 | Precio: 357.32 | Vol: 881,495 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-21 09:30:00-04:00 | Precio: 354.18 | Vol: 1,866,925 | 🎯 TP Limit: $4.500
[JPM] 📅 2026-08-27 15:30:00-04:00 | Precio: 354.05 | Vol: 645,064 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-09 09:30:00-04:00 | Precio: 54.35 | Vol: 6,627,644 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-16 09:30:00-04:00 | Precio: 56.56 | Vol: 5,129,881 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-16 15:30:00-04:00 | Precio: 56.85 | Vol: 3,978,554 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-23 09:30:00-04:00 | Precio: 57.58 | Vol: 7,402,740 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-06-29 09:30:00-04:00 | Precio: 58.21 | Vol: 6,134,576 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-01 09:30:00-04:00 | Precio: 57.82 | Vol: 5,814,747 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-01 15:30:00-04:00 | Precio: 58.38 | Vol: 5,454,043 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-09 09:30:00-04:00 | Precio: 59.07 | Vol: 3,411,896 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-10 09:30:00-04:00 | Precio: 59.72 | Vol: 2,731,521 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-14 14:30:00-04:00 | Precio: 60.60 | Vol: 4,247,601 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-15 15:30:00-04:00 | Precio: 61.62 | Vol: 5,166,054 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-16 12:30:00-04:00 | Precio: 61.67 | Vol: 6,480,286 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-17 09:30:00-04:00 | Precio: 61.88 | Vol: 8,920,215 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-17 15:30:00-04:00 | Precio: 61.28 | Vol: 7,870,959 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-22 09:30:00-04:00 | Precio: 61.47 | Vol: 4,959,003 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-22 15:30:00-04:00 | Precio: 61.65 | Vol: 5,720,207 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-07-24 15:30:00-04:00 | Precio: 62.04 | Vol: 4,169,627 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-05 09:30:00-04:00 | Precio: 63.42 | Vol: 6,740,226 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-19 15:30:00-04:00 | Precio: 63.19 | Vol: 3,825,887 | 🎯 TP Limit: $4.500
[BAC] 📅 2026-08-28 09:30:00-04:00 | Precio: 61.78 | Vol: 8,472,765 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-06-12 09:30:00-04:00 | Precio: 83.23 | Vol: 1,584,006 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-06-16 15:30:00-04:00 | Precio: 85.06 | Vol: 1,764,679 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-06-25 14:30:00-04:00 | Precio: 84.79 | Vol: 1,298,034 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-06-29 09:30:00-04:00 | Precio: 84.38 | Vol: 3,374,088 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-13 14:30:00-04:00 | Precio: 87.17 | Vol: 1,386,074 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-14 15:30:00-04:00 | Precio: 85.36 | Vol: 5,415,557 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-17 09:30:00-04:00 | Precio: 89.32 | Vol: 4,741,091 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-17 15:30:00-04:00 | Precio: 87.52 | Vol: 3,579,183 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-21 09:30:00-04:00 | Precio: 87.03 | Vol: 2,702,042 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-22 15:30:00-04:00 | Precio: 86.43 | Vol: 2,940,076 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-28 15:30:00-04:00 | Precio: 86.92 | Vol: 1,945,634 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-07-30 15:30:00-04:00 | Precio: 85.43 | Vol: 2,387,635 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-04 14:30:00-04:00 | Precio: 88.69 | Vol: 1,108,147 | 🎯 TP Limit: $4.500
[WFC] 📅 2026-08-19 15:30:00-04:00 | Precio: 85.95 | Vol: 1,695,257 | 🎯 TP Limit: $4.500
[C] 📅 2026-06-16 15:30:00-04:00 | Precio: 142.99 | Vol: 1,684,281 | 🎯 TP Limit: $4.500
[C] 📅 2026-06-22 09:30:00-04:00 | Precio: 145.72 | Vol: 2,009,600 | 🎯 TP Limit: $4.500
[C] 📅 2026-06-26 15:30:00-04:00 | Precio: 141.67 | Vol: 2,098,593 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-09 09:30:00-04:00 | Precio: 139.01 | Vol: 1,458,601 | 🎯 TP Limit: $4.500
[C] 📅 2026-07-13 12:30:00-04:00 | Precio: 138.48 | Vol: 1,101,047 | 🎯 TP Limit: $4.500

In [14]:
import pandas as pd
import yfinance as yf
import warnings

# Silenciar advertencias secundarias de Pandas/Yfinance
warnings.simplefilter(action='ignore', category=FutureWarning)

universo_activos = [
    "SPY", "QQQ", "DIA",
    "AAPL", "AMZN", "GOOG", "MSFT", "NFLX",
    "CMG", "WMT", "COST", "MCD", "NKE",
    "JPM", "BAC", "WFC", "C",
    "JNJ", "KO", "PEP", "F"
]

print("==========================================================================")
print("      MATRIZ MAESTRA UNIFICADA - TODAS LAS ESTRATEGIAS ACTIVAS             ")
print("==========================================================================")

todas_las_senales = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        # Descarga limpia configurando auto_adjust
        df = yf.download(ticker, period="60d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # 1. Pullback SMA 40 (CALL)
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"]) & (df["SMA_100"] > df["SMA_200"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        # 2. Estrategia 1: Ruptura sobre piso fuerte
        soporte_fuerte = df["Low"].rolling(window=20).min()
        max_dec = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        s_est1 = max_dec & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        # 3. Estrategia 2: Ruptura de rango con volumen
        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_est2 = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        # 4. Estrategia 5: Patrón Hammer
        cuerpo = abs(df["Close"] - df["Open"])
        sombra_inf = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_sup = df["High"] - df[["Open", "Close"]].max(axis=1)
        es_hammer = (cuerpo > 0) & (sombra_inf >= (2 * cuerpo)) & (sombra_sup <= (0.5 * cuerpo))
        s_hammer = (df["Close"] < df["Close"].shift(5)) & es_hammer.shift(1) & (df["High"] > df["High"].shift(1))

        # Registrar cada tipo de señal encontrada
        for idx, row in df[s_call].iterrows():
            todas_las_senales.append({"Ticker": ticker, "Estrategia": "Pullback SMA40 (CALL)", "Fecha": idx, "Precio": round(row["Close"], 2), "TP Limit": round(calcular_take_profit(), 3)})
        for idx, row in df[s_est1].iterrows():
            todas_las_senales.append({"Ticker": ticker, "Estrategia": "Estrategia 1 (Piso Fuerte)", "Fecha": idx, "Precio": round(row["Close"], 2), "TP Limit": round(calcular_take_profit(), 3)})
        for idx, row in df[s_est2].iterrows():
            todas_las_senales.append({"Ticker": ticker, "Estrategia": "Estrategia 2 (Ruptura Rango)", "Fecha": idx, "Precio": round(row["Close"], 2), "TP Limit": round(calcular_take_profit(), 3)})
        for idx, row in df[s_hammer].iterrows():
            todas_las_senales.append({"Ticker": ticker, "Estrategia": "Estrategia 5 (Hammer)", "Fecha": idx, "Precio": round(row["Close"], 2), "TP Limit": round(calcular_take_profit(), 3)})

    except Exception as e:
        continue

# Generar y mostrar la tabla consolidada
df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    pd.set_option('display.max_rows', None)
    print(df_final.to_string(index=False))
    print(f"\n📊 TOTAL GENERAL DE SEÑALES UNIFICADAS: {len(df_final)}")
else:
    print("No se encontraron señales activas en este bloque.")
print("==========================================================================")

==========================================================================
      MATRIZ MAESTRA UNIFICADA - TODAS LAS ESTRATEGIAS ACTIVAS
==========================================================================
Ticker                   Estrategia                     Fecha  Precio  TP Limit
   SPY        Pullback SMA40 (CALL) 2026-08-12 12:30:00-04:00  772.78       4.5
   SPY        Pullback SMA40 (CALL) 2026-08-12 13:30:00-04:00  773.09       4.5
   SPY        Pullback SMA40 (CALL) 2026-08-13 09:30:00-04:00  779.19       4.5
   SPY        Pullback SMA40 (CALL) 2026-08-14 14:30:00-04:00  776.16       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-06-11 09:30:00-04:00  728.82       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-06-17 09:30:00-04:00  751.69       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-06-18 15:30:00-04:00  746.59       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-06-24 09:30:00-04:00  736.49       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-06-26 09:30:00-04:00  733.49       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-07-02 09:30:00-04:00  747.94       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-07-15 09:30:00-04:00  754.62       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-07-16 15:30:00-04:00  750.76       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-07-17 11:30:00-04:00  745.94       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-07-23 15:30:00-04:00  738.17       4.5
   SPY   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  771.04       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-06-30 09:30:00-04:00  744.48       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-08-03 09:30:00-04:00  754.50       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-08-04 09:30:00-04:00  764.49       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-08-13 09:30:00-04:00  779.19       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-08-27 09:30:00-04:00  769.67       4.5
   SPY Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  774.95       4.5
   SPY        Estrategia 5 (Hammer) 2026-06-05 13:30:00-04:00  740.90       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-06-11 09:30:00-04:00  702.12       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-06-15 09:30:00-04:00  740.99       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-06-24 09:30:00-04:00  715.15       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-07-08 09:30:00-04:00  707.20       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-07-10 09:30:00-04:00  722.45       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-07-23 15:30:00-04:00  691.80       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-08-04 09:30:00-04:00  716.01       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-08-07 09:30:00-04:00  721.25       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-08-11 15:30:00-04:00  718.34       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-08-18 12:30:00-04:00  718.35       4.5
   QQQ   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  721.06       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-06-15 09:30:00-04:00  740.99       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-06-30 09:30:00-04:00  732.99       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-03 11:30:00-04:00  698.49       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-04 09:30:00-04:00  716.01       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-04 10:30:00-04:00  717.99       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-13 09:30:00-04:00  732.96       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-27 09:30:00-04:00  718.93       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-27 15:30:00-04:00  721.06       4.5
   QQQ Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  723.41       4.5
   QQQ        Estrategia 5 (Hammer) 2026-06-17 13:30:00-04:00  728.69       4.5
   QQQ        Estrategia 5 (Hammer) 2026-07-01 11:30:00-04:00  729.23       4.5
   QQQ        Estrategia 5 (Hammer) 2026-07-02 14:30:00-04:00  709.85       4.5
   DIA        Pullback SMA40 (CALL) 2026-07-16 15:30:00-04:00  524.78       4.5
   DIA        Pullback SMA40 (CALL) 2026-07-17 09:30:00-04:00  524.56       4.5
   DIA        Pullback SMA40 (CALL) 2026-08-10 10:30:00-04:00  539.70       4.5
   DIA        Pullback SMA40 (CALL) 2026-08-10 15:30:00-04:00  539.02       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-09 12:30:00-04:00  506.70       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-11 09:30:00-04:00  503.28       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-16 09:30:00-04:00  521.24       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-17 09:30:00-04:00  523.68       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-23 09:30:00-04:00  517.77       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-26 09:30:00-04:00  519.82       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-06-29 09:30:00-04:00  521.67       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-01 09:30:00-04:00  523.30       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-02 09:30:00-04:00  525.67       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-09 09:30:00-04:00  523.87       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-21 09:30:00-04:00  521.12       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-22 09:30:00-04:00  522.39       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-07-23 14:30:00-04:00  516.27       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-08-05 09:30:00-04:00  545.93       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-08-07 09:30:00-04:00  540.19       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-08-17 11:30:00-04:00  535.36       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-08-21 09:30:00-04:00  530.78       4.5
   DIA   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  535.17       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-06-12 10:30:00-04:00  514.92       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-06-15 09:30:00-04:00  519.31       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-06-16 09:30:00-04:00  521.24       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-06-17 09:30:00-04:00  523.68       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-06-25 09:30:00-04:00  525.89       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-07-01 09:30:00-04:00  523.30       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-07-02 15:30:00-04:00  527.83       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-07-28 10:30:00-04:00  527.17       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-08-03 09:30:00-04:00  530.53       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-08-05 09:30:00-04:00  545.93       4.5
   DIA Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  537.47       4.5
   DIA        Estrategia 5 (Hammer) 2026-06-08 14:30:00-04:00  508.93       4.5
   DIA        Estrategia 5 (Hammer) 2026-06-26 11:30:00-04:00  518.90       4.5
   DIA        Estrategia 5 (Hammer) 2026-07-07 14:30:00-04:00  527.84       4.5
   DIA        Estrategia 5 (Hammer) 2026-07-20 11:30:00-04:00  519.80       4.5
   DIA        Estrategia 5 (Hammer) 2026-07-22 09:30:00-04:00  522.39       4.5
   DIA        Estrategia 5 (Hammer) 2026-08-17 14:30:00-04:00  534.30       4.5
  AAPL        Pullback SMA40 (CALL) 2026-07-20 13:30:00-04:00  325.94       4.5
  AAPL        Pullback SMA40 (CALL) 2026-07-20 14:30:00-04:00  329.02       4.5
  AAPL        Pullback SMA40 (CALL) 2026-07-21 11:30:00-04:00  328.62       4.5
  AAPL        Pullback SMA40 (CALL) 2026-07-21 14:30:00-04:00  327.93       4.5
  AAPL        Pullback SMA40 (CALL) 2026-07-30 15:30:00-04:00  333.85       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-06-18 09:30:00-04:00  299.61       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-06-23 09:30:00-04:00  300.51       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-06-25 13:30:00-04:00  279.35       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-06-30 15:30:00-04:00  289.09       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-07-24 14:30:00-04:00  332.49       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-07-28 15:30:00-04:00  340.16       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-08-04 09:30:00-04:00  306.81       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-08-12 15:30:00-04:00  302.23       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-08-19 14:30:00-04:00  316.68       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-08-26 14:30:00-04:00  314.84       4.5
  AAPL   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  314.58       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-02 09:30:00-04:00  305.05       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-02 10:30:00-04:00  305.42       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-06 09:30:00-04:00  311.73       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-13 09:30:00-04:00  320.19       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-15 09:30:00-04:00  324.71       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-15 11:30:00-04:00  328.17       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-16 09:30:00-04:00  330.37       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-24 10:30:00-04:00  331.77       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-24 11:30:00-04:00  333.72       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-27 09:30:00-04:00  337.69       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-07-27 10:30:00-04:00  338.74       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-08-18 10:30:00-04:00  310.43       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-08-19 09:30:00-04:00  316.01       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-08-26 14:30:00-04:00  314.84       4.5
  AAPL Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  321.94       4.5
  AAPL        Estrategia 5 (Hammer) 2026-06-09 14:30:00-04:00  291.13       4.5
  AAPL        Estrategia 5 (Hammer) 2026-07-20 13:30:00-04:00  325.94       4.5
  AAPL        Estrategia 5 (Hammer) 2026-08-20 09:30:00-04:00  316.47       4.5
  AMZN        Pullback SMA40 (CALL) 2026-07-20 11:30:00-04:00  252.48       4.5
  AMZN        Pullback SMA40 (CALL) 2026-08-06 15:30:00-04:00  272.20       4.5
  AMZN        Pullback SMA40 (CALL) 2026-08-07 09:30:00-04:00  276.15       4.5
  AMZN        Pullback SMA40 (CALL) 2026-08-07 10:30:00-04:00  278.19       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-06-09 12:30:00-04:00  243.51       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-06-26 15:30:00-04:00  230.55       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-02 09:30:00-04:00  244.07       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-20 09:30:00-04:00  249.45       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-22 14:30:00-04:00  244.59       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-23 11:30:00-04:00  234.80       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-23 15:30:00-04:00  233.56       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-07-30 14:30:00-04:00  239.52       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-08-10 15:30:00-04:00  278.08       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-08-19 09:30:00-04:00  261.17       4.5
  AMZN   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  256.22       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-06-15 09:30:00-04:00  246.12       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-06-29 09:30:00-04:00  244.14       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-07-15 09:30:00-04:00  254.75       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-07-15 10:30:00-04:00  255.82       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-07-30 09:30:00-04:00  237.31       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-07-30 14:30:00-04:00  239.52       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-07-31 09:30:00-04:00  269.63       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-08-03 09:30:00-04:00  285.84       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-08-19 15:30:00-04:00  265.89       4.5
  AMZN Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  266.85       4.5
  AMZN        Estrategia 5 (Hammer) 2026-06-04 14:30:00-04:00  253.79       4.5
  AMZN        Estrategia 5 (Hammer) 2026-07-23 12:30:00-04:00  234.49       4.5
  AMZN        Estrategia 5 (Hammer) 2026-08-04 12:30:00-04:00  278.75       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-06-15 09:30:00-04:00  367.00       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-06-16 09:30:00-04:00  368.43       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-06-17 13:30:00-04:00  363.70       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-06-22 12:30:00-04:00  346.32       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-06-26 14:30:00-04:00  341.12       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-07-08 15:30:00-04:00  358.60       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-07-14 09:30:00-04:00  353.77       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-07-16 09:30:00-04:00  372.24       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-07-23 11:30:00-04:00  320.97       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-07-24 09:30:00-04:00  319.87       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-08-13 15:30:00-04:00  343.98       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-08-19 10:30:00-04:00  342.07       4.5
  GOOG   Estrategia 1 (Piso Fuerte) 2026-08-27 15:30:00-04:00  337.55       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-06-15 09:30:00-04:00  367.00       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-01 09:30:00-04:00  356.74       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-06 14:30:00-04:00  365.16       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-07 09:30:00-04:00  368.45       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-15 09:30:00-04:00  364.21       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-15 10:30:00-04:00  369.39       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-15 11:30:00-04:00  371.23       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-16 09:30:00-04:00  372.24       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-31 09:30:00-04:00  347.12       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-31 10:30:00-04:00  348.46       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-31 13:30:00-04:00  356.05       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-07-31 15:30:00-04:00  356.71       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-08-03 09:30:00-04:00  367.42       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-08-24 09:30:00-04:00  345.39       4.5
  GOOG Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  344.95       4.5
  GOOG        Estrategia 5 (Hammer) 2026-06-16 09:30:00-04:00  368.43       4.5
  GOOG        Estrategia 5 (Hammer) 2026-06-17 13:30:00-04:00  363.70       4.5
  GOOG        Estrategia 5 (Hammer) 2026-06-30 15:30:00-04:00  353.32       4.5
  GOOG        Estrategia 5 (Hammer) 2026-07-09 12:30:00-04:00  352.54       4.5
  GOOG        Estrategia 5 (Hammer) 2026-08-12 12:30:00-04:00  341.67       4.5
  MSFT        Pullback SMA40 (CALL) 2026-07-20 11:30:00-04:00  401.49       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-06-11 13:30:00-04:00  388.81       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-06-23 09:30:00-04:00  376.28       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-06-25 13:30:00-04:00  357.72       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-07-02 09:30:00-04:00  388.65       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-07-15 09:30:00-04:00  395.04       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-07-28 09:30:00-04:00  395.52       4.5
  MSFT   Estrategia 1 (Piso Fuerte) 2026-07-31 09:30:00-04:00  453.32       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-01 09:30:00-04:00  382.30       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-07 09:30:00-04:00  393.92       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-15 09:30:00-04:00  395.04       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-28 09:30:00-04:00  395.52       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-30 09:30:00-04:00  449.89       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-07-30 11:30:00-04:00  455.29       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-03 09:30:00-04:00  484.79       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-04 09:30:00-04:00  493.70       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-06 15:30:00-04:00  499.86       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-07 09:30:00-04:00  504.10       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-10 09:30:00-04:00  512.43       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-26 09:30:00-04:00  493.65       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-27 09:30:00-04:00  505.06       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-28 09:30:00-04:00  510.72       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-28 10:30:00-04:00  515.31       4.5
  MSFT Estrategia 2 (Ruptura Rango) 2026-08-28 11:30:00-04:00  516.49       4.5
  MSFT        Estrategia 5 (Hammer) 2026-06-17 13:30:00-04:00  383.02       4.5
  MSFT        Estrategia 5 (Hammer) 2026-07-14 12:30:00-04:00  386.74       4.5
  MSFT        Estrategia 5 (Hammer) 2026-08-18 09:30:00-04:00  481.15       4.5
  NFLX        Pullback SMA40 (CALL) 2026-08-13 09:30:00-04:00   77.17       4.5
  NFLX        Pullback SMA40 (CALL) 2026-08-18 10:30:00-04:00   78.75       4.5
  NFLX        Pullback SMA40 (CALL) 2026-08-25 10:30:00-04:00   81.64       4.5
  NFLX        Pullback SMA40 (CALL) 2026-08-25 14:30:00-04:00   82.21       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-06-16 14:30:00-04:00   78.50       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-06-18 09:30:00-04:00   77.11       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-06-22 13:30:00-04:00   73.18       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-06-29 09:30:00-04:00   75.66       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-07-01 09:30:00-04:00   73.12       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-07-10 13:30:00-04:00   73.38       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-07-15 09:30:00-04:00   74.74       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-07-28 09:30:00-04:00   73.57       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-11 15:30:00-04:00   74.78       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-13 12:30:00-04:00   77.20       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-17 15:30:00-04:00   76.03       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-19 09:30:00-04:00   80.22       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-20 09:30:00-04:00   80.28       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-24 09:30:00-04:00   80.31       4.5
  NFLX   Estrategia 1 (Piso Fuerte) 2026-08-25 09:30:00-04:00   81.57       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-06-26 09:30:00-04:00   74.38       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-06-26 10:30:00-04:00   74.71       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-06-29 09:30:00-04:00   75.66       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-07-02 09:30:00-04:00   76.20       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-07-02 12:30:00-04:00   78.11       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-07-22 09:30:00-04:00   70.25       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-07-28 09:30:00-04:00   73.57       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-10 15:30:00-04:00   76.30       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-13 09:30:00-04:00   77.17       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-13 15:30:00-04:00   78.23       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-18 10:30:00-04:00   78.75       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-19 09:30:00-04:00   80.22       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-19 10:30:00-04:00   80.62       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-25 09:30:00-04:00   81.57       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-25 10:30:00-04:00   81.64       4.5
  NFLX Estrategia 2 (Ruptura Rango) 2026-08-25 11:30:00-04:00   82.17       4.5
  NFLX        Estrategia 5 (Hammer) 2026-06-24 13:30:00-04:00   72.71       4.5
  NFLX        Estrategia 5 (Hammer) 2026-06-30 11:30:00-04:00   72.91       4.5
  NFLX        Estrategia 5 (Hammer) 2026-07-31 13:30:00-04:00   71.66       4.5
  NFLX        Estrategia 5 (Hammer) 2026-08-20 11:30:00-04:00   80.33       4.5
   CMG        Pullback SMA40 (CALL) 2026-08-27 14:30:00-04:00   37.21       4.5

In [15]:
# --- EXPORTAR Y RESUMIR LA MATRIZ MAESTRA ---

# 1. Agrupar por Ticker y Estrategia para ver el desglose exacto
resumen_estrategias = df_final.groupby(["Ticker", "Estrategia"]).size().reset_index(name="Total_Señales")

print("==================================================")
print("        RESUMEN INSTITUCIONAL POR ACTIVO          ")
print("==================================================")
print(resumen_estrategias.to_string(index=False))

# 2. Exportar automáticamente a un archivo CSV en tu Colab para abrir en Excel
nombre_archivo = "Plan_Maestro_Señales_Unificadas.csv"
df_final.to_csv(nombre_archivo, index=False)
print(f"\n📁 ¡Archivo exportado con éxito! Puedes descargarlo desde la pestaña de archivos de Colab: '{nombre_archivo}'")

==================================================
        RESUMEN INSTITUCIONAL POR ACTIVO
==================================================
Ticker                   Estrategia  Total_Señales
  AAPL   Estrategia 1 (Piso Fuerte)             11
  AAPL Estrategia 2 (Ruptura Rango)             15
  AAPL        Estrategia 5 (Hammer)              3
  AAPL        Pullback SMA40 (CALL)              5
  AMZN   Estrategia 1 (Piso Fuerte)             11
  AMZN Estrategia 2 (Ruptura Rango)             10
  AMZN        Estrategia 5 (Hammer)              3
  AMZN        Pullback SMA40 (CALL)              4
   BAC   Estrategia 1 (Piso Fuerte)             20
   BAC Estrategia 2 (Ruptura Rango)             17
   BAC        Estrategia 5 (Hammer)              4
   BAC        Pullback SMA40 (CALL)             16
     C   Estrategia 1 (Piso Fuerte)             12
     C Estrategia 2 (Ruptura Rango)             14
     C        Estrategia 5 (Hammer)              5
   CMG   Estrategia 1 (Piso Fuerte)             12
   CMG Estrategia 2 (Ruptura Rango)             18
   CMG        Estrategia 5 (Hammer)              2
   CMG        Pullback SMA40 (CALL)              3
  COST   Estrategia 1 (Piso Fuerte)             18
  COST Estrategia 2 (Ruptura Rango)             12
  COST        Estrategia 5 (Hammer)              5
  COST        Pullback SMA40 (CALL)              3
   DIA   Estrategia 1 (Piso Fuerte)             18
   DIA Estrategia 2 (Ruptura Rango)             11
   DIA        Estrategia 5 (Hammer)              6
   DIA        Pullback SMA40 (CALL)              4
     F   Estrategia 1 (Piso Fuerte)             14
     F Estrategia 2 (Ruptura Rango)              8
     F        Estrategia 5 (Hammer)              4
     F        Pullback SMA40 (CALL)              2
  GOOG   Estrategia 1 (Piso Fuerte)             13
  GOOG Estrategia 2 (Ruptura Rango)             15
  GOOG        Estrategia 5 (Hammer)              5
   JNJ   Estrategia 1 (Piso Fuerte)             12
   JNJ Estrategia 2 (Ruptura Rango)             16
   JNJ        Estrategia 5 (Hammer)              5
   JNJ        Pullback SMA40 (CALL)              9
   JPM   Estrategia 1 (Piso Fuerte)             20
   JPM Estrategia 2 (Ruptura Rango)             14
   JPM        Estrategia 5 (Hammer)              3
   JPM        Pullback SMA40 (CALL)             14
    KO   Estrategia 1 (Piso Fuerte)             14
    KO Estrategia 2 (Ruptura Rango)             18
    KO        Estrategia 5 (Hammer)              3
   MCD   Estrategia 1 (Piso Fuerte)             15
   MCD Estrategia 2 (Ruptura Rango)              9
   MCD        Estrategia 5 (Hammer)              6
  MSFT   Estrategia 1 (Piso Fuerte)              7
  MSFT Estrategia 2 (Ruptura Rango)             16
  MSFT        Estrategia 5 (Hammer)              3
  MSFT        Pullback SMA40 (CALL)              1
  NFLX   Estrategia 1 (Piso Fuerte)             15
  NFLX Estrategia 2 (Ruptura Rango)             16
  NFLX        Estrategia 5 (Hammer)              4
  NFLX        Pullback SMA40 (CALL)              4
   NKE   Estrategia 1 (Piso Fuerte)             14
   NKE Estrategia 2 (Ruptura Rango)              9
   NKE        Estrategia 5 (Hammer)              4
   PEP   Estrategia 1 (Piso Fuerte)             13
   PEP Estrategia 2 (Ruptura Rango)             10
   PEP        Estrategia 5 (Hammer)              5
   PEP        Pullback SMA40 (CALL)              1
   QQQ   Estrategia 1 (Piso Fuerte)             11
   QQQ Estrategia 2 (Ruptura Rango)              9
   QQQ        Estrategia 5 (Hammer)              3
   SPY   Estrategia 1 (Piso Fuerte)             11
   SPY Estrategia 2 (Ruptura Rango)              6
   SPY        Estrategia 5 (Hammer)              1
   SPY        Pullback SMA40 (CALL)              4
   WFC   Estrategia 1 (Piso Fuerte)             14
   WFC Estrategia 2 (Ruptura Rango)             12
   WFC        Estrategia 5 (Hammer)              4
   WFC        Pullback SMA40 (CALL)              8
   WMT   Estrategia 1 (Piso Fuerte)              9
   WMT Estrategia 2 (Ruptura Rango)             10
   WMT        Estrategia 5 (Hammer)              2
   WMT        Pullback SMA40 (CALL)              3

📁 ¡Archivo exportado con éxito! Puedes descargarlo desde la pestaña de archivos de Colab: 'Plan_Maestro_Señales_Unificadas.csv'

In [16]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
TELEGRAM_TOKEN = "AAH5diJ9nkG7ySF4Z8AVdtS-8ZvsZYVv0pQ"       # Pega aquí el token de BotFather entre comillas
CHAT_ID = "8642681599"                 # ¡Tu Chat ID ya está configurado aquí!

def enviar_alerta_telegram(mensaje):
    """Función para enviar mensajes automáticos a tu Telegram"""
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = [
    "SPY", "QQQ", "DIA",
    "AAPL", "AMZN", "GOOG", "MSFT", "NFLX",
    "CMG", "WMT", "COST", "MCD", "NKE",
    "JPM", "BAC", "WFC", "C",
    "JNJ", "KO", "PEP", "F"
]

print("==========================================================================")
print("     MATRIZ MAESTRA CON ALERTA AUTOMATIZADA DE TELEGRAM ACTIVA             ")
print("==========================================================================")

todas_las_senales = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # Estrategias
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"]) & (df["SMA_100"] > df["SMA_200"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        soporte_fuerte = df["Low"].rolling(window=20).min()
        max_dec = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        s_est1 = max_dec & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_est2 = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        cuerpo = abs(df["Close"] - df["Open"])
        sombra_inf = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_sup = df["High"] - df[["Open", "Close"]].max(axis=1)
        es_hammer = (cuerpo > 0) & (sombra_inf >= (2 * cuerpo)) & (sombra_sup <= (0.5 * cuerpo))
        s_hammer = (df["Close"] < df["Close"].shift(5)) & es_hammer.shift(1) & (df["High"] > df["High"].shift(1))

        estrategias_activas = [
            (s_call, "Pullback SMA40 (CALL)"),
            (s_est1, "Estrategia 1 (Piso Fuerte)"),
            (s_est2, "Estrategia 2 (Ruptura Rango)"),
            (s_hammer, "Estrategia 5 (Hammer)")
        ]

        for condicion, nombre_est in estrategias_activas:
            for idx, row in df[condicion].iterrows():
                tp_val = round(calcular_take_profit(), 3)
                precio_val = round(row["Close"], 2)
                todas_las_senales.append({"Ticker": ticker, "Estrategia": nombre_est, "Fecha": idx, "Precio": precio_val, "TP Limit": tp_val})

    except Exception as e:
        continue

df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    print(f"\n📊 TOTAL DE SEÑALES ENCONTRADAS: {len(df_final)}")
    ultimas_senales = df_final.tail(5)

    mensaje_telegram = "🚨 *NUEVAS SEÑALES DE TRADING DETECTADAS* 🚨\n\n"
    for _, r in ultimas_senales.iterrows():
        mensaje_telegram += f"📌 *{r['Ticker']}* | {r['Estrategia']}\n" \
                            f"📅 {r['Fecha']}\n" \
                            f"💵 Precio: `${r['Precio']}` | 🎯 TP: `${r['TP Limit']}`\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Alerta enviada a Telegram con éxito!")
else:
    print("No se encontraron señales activas.")
print("==========================================================================")

==========================================================================
     MATRIZ MAESTRA CON ALERTA AUTOMATIZADA DE TELEGRAM ACTIVA
==========================================================================

📊 TOTAL DE SEÑALES ENCONTRADAS: 710
📲 ¡Alerta enviada a Telegram con éxito!
==========================================================================

In [17]:
import requests

TELEGRAM_TOKEN = "8556809936:AAH5diJ9nkG7ySF4Z8AVdt

S-8ZvsZYVv0pQ"  # Pon tu token aquí
CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, esto es una prueba directa desde Colab 🚀",
}

response = requests.post(url, json=payload)
print(response.json())

SyntaxError: unterminated string literal (detected at line 3) (1024194122.py, line 3)

In [ ]:
import requests

TELEGRAM_TOKEN = "8556809936:AAH5diJ9nkG7ySF4Z8AVdtS-8ZvsZYVv0pQ"
CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, prueba directa desde Colab 🚀 ¡Sistema de trading conectado!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

TELEGRAM_TOKEN = "8556809936:AAH5diJ9nkG7ySF4Z8AVdtS-8ZvsZYVv0pQ"
CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, prueba directa desde Colab 🚀 ¡Sistema conectado!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

TELEGRAM_TOKEN = "TU_TOKEN_AQUI"  # Pon tu token aquí
CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, esto es una prueba directa desde Colab 🚀",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

TELEGRAM_TOKEN = "8556809936:AAH5diJ9nkG7ySF4Z8AVdtS-8ZvsZYVv0pQ"
CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, prueba directa desde Colab 🚀 ¡Sistema conectado!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

token_part1 = "8556809936:AAH5diJ9nkG7ySF4Z8AVdt"
token_part2 = "S-8ZvsZYVv0pQ"
TELEGRAM_TOKEN = token_part1 + token_part2

CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz, prueba directa desde Colab 🚀 ¡Sistema conectado!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

# Unimos el token limpiamente en una sola línea mediante código
p1 = "8556809936:AAH5diJ9nkG7ySF4Z8AVdt"
p2 = "S-8ZvsZYVv0pQ"
TELEGRAM_TOKEN = p1 + p2

CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz 🚀 ¡Prueba final conectada con éxito!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import requests

# Unimos tu nuevo token limpio en dos partes para evitar saltos de línea
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2

CHAT_ID = "8642681599"

url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
payload = {
    "chat_id": CHAT_ID,
    "text": "Hola Franz 🚀 ¡Prueba con el nuevo token definitivo!",
}

response = requests.post(url, json=payload)
print(response.json())

In [ ]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM (CON TOKEN LIMPIO) ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

def enviar_alerta_telegram(mensaje):
    """Función para enviar mensajes automáticos a tu Telegram"""
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = [
    "SPY", "QQQ", "DIA",
    "AAPL", "AMZN", "GOOG", "MSFT", "NFLX",
    "CMG", "WMT", "COST", "MCD", "NKE",
    "JPM", "BAC", "WFC", "C",
    "JNJ", "KO", "PEP", "F"
]

print("==========================================================================")
print("     MATRIZ MAESTRA CON ALERTA AUTOMATIZADA DE TELEGRAM ACTIVA             ")
print("==========================================================================")

todas_las_senales = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # Estrategias
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"]) & (df["SMA_100"] > df["SMA_200"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        soporte_fuerte = df["Low"].rolling(window=20).min()
        max_dec = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        s_est1 = max_dec & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_est2 = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        cuerpo = abs(df["Close"] - df["Open"])
        sombra_inf = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_sup = df["High"] - df[["Open", "Close"]].max(axis=1)
        es_hammer = (cuerpo > 0) & (sombra_inf >= (2 * cuerpo)) & (sombra_sup <= (0.5 * cuerpo))
        s_hammer = (df["Close"] < df["Close"].shift(5)) & es_hammer.shift(1) & (df["High"] > df["High"].shift(1))

        estrategias_activas = [
            (s_call, "Pullback SMA40 (CALL)"),
            (s_est1, "Estrategia 1 (Piso Fuerte)"),
            (s_est2, "Estrategia 2 (Ruptura Rango)"),
            (s_hammer, "Estrategia 5 (Hammer)")
        ]

        for condicion, nombre_est in estrategias_activas:
            for idx, row in df[condicion].iterrows():
                tp_val = round(calcular_take_profit(), 3)
                precio_val = round(row["Close"], 2)
                todas_las_senales.append({"Ticker": ticker, "Estrategia": nombre_est, "Fecha": idx, "Precio": precio_val, "TP Limit": tp_val})

    except Exception as e:
        continue

df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    print(f"\n📊 TOTAL DE SEÑALES ENCONTRADAS: {len(df_final)}")
    ultimas_senales = df_final.tail(5)

    mensaje_telegram = "🚨 *NUEVAS SEÑALES DE TRADING DETECTADAS* 🚨\n\n"
    for _, r in ultimas_senales.iterrows():
        mensaje_telegram += f"📌 *{r['Ticker']}* | {r['Estrategia']}\n" \
                            f"📅 {r['Fecha']}\n" \
                            f"💵 Precio: `${r['Precio']}` | 🎯 TP: `${r['TP Limit']}`\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Alerta enviada a Telegram con éxito!")
else:
    print("No se encontraron señales activas.")
print("==========================================================================")

In [ ]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Diccionario para traducir los códigos raros a nombres fáciles
nombres_amigables = {
    "SPY": "S&P 500 (Las 500 empresas más grandes de EE.UU.)",
    "QQQ": "Invesco QQQ (Las 100 mayores empresas de tecnología, como Apple y Microsoft)",
    "DIA": "Dow Jones (Las 30 empresas industriales más famosas de EE.UU.)",
    "AAPL": "Apple (Fabricantes del iPhone)",
    "AMZN": "Amazon (La tienda gigante de internet)",
    "GOOG": "Google (El buscador y YouTube)",
    "MSFT": "Microsoft (Dueños de Windows y Xbox)",
    "NFLX": "Netflix (Películas y series en streaming)",
    "CMG": "Chipotle (Restaurantes de comida)",
    "WMT": "Walmart (Supermercados gigantes)",
    "COST": "Costco (Tiendas grandes al por mayor)",
    "MCD": "McDonald's (Hamburguesas)",
    "NKE": "Nike (Zapatillas y ropa deportiva)",
    "JPM": "JPMorgan Chase (Banco muy grande)",
    "BAC": "Bank of America (Banco de América)",
    "WFC": "Wells Fargo (Banco americano)",
    "C": "Citigroup (Banco global)",
    "JNJ": "Johnson & Johnson (Productos de salud y medicinas)",
    "KO": "Coca-Cola (El famoso refresco)",
    "PEP": "PepsiCo (Pepsi y snacks como Lay's)",
    "F": "Ford (La fábrica de coches)"
}

# Explicaciones sencillas para niños de cada estrategia
explicaciones_estrategias = {
    "Pullback SMA40 (CALL)": "El precio bajó un poquito para tomar carrerilla y ahora parece que va a volver a subir con fuerza.",
    "Estrategia 1 (Piso Fuerte)": "La acción tocó un suelo muy sólido donde los compradores dijeron '¡de aquí no pasa!' y empezaron a comprar.",
    "Estrategia 2 (Ruptura Rango)": "Rompió su récord de precio anterior con mucha gente comprando a la vez. ¡Va con ganas de subir más!",
    "Estrategia 5 (Hammer)": "Hizo forma de 'martillo': los vendedores intentaron tirar el precio abajo pero los compradores barrieron y lo subieron."
}

def enviar_alerta_telegram(mensaje):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = list(nombres_amigables.keys())

print("==========================================================================")
print("     MATRIZ MAESTRA - EXPLICACIONES PARA TODOS (MODO SENCILLO)            ")
print("==========================================================================")

todas_las_senales = []

def calcular_take_profit(num_contratos=10, precio_contrato_inicial=0.30):
    comision_total = 7.00 + (1.25 * num_contratos)
    inversion_neta = (num_contratos * precio_contrato_inicial) + comision_total
    return (inversion_neta / num_contratos) * 2

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # Estrategias
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"]) & (df["SMA_100"] > df["SMA_200"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        max_dec = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        s_est1 = max_dec & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_est2 = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        cuerpo = abs(df["Close"] - df["Open"])
        sombra_inf = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_sup = df["High"] - df[["Open", "Close"]].max(axis=1)
        es_hammer = (cuerpo > 0) & (sombra_inf >= (2 * cuerpo)) & (sombra_sup <= (0.5 * cuerpo))
        s_hammer = (df["Close"] < df["Close"].shift(5)) & es_hammer.shift(1) & (df["High"] > df["High"].shift(1))

        estrategias_activas = [
            (s_call, "Pullback SMA40 (CALL)"),
            (s_est1, "Estrategia 1 (Piso Fuerte)"),
            (s_est2, "Estrategia 2 (Ruptura Rango)"),
            (s_hammer, "Estrategia 5 (Hammer)")
        ]

        for condicion, nombre_est in estrategias_activas:
            for idx, row in df[condicion].iterrows():
                tp_val = round(calcular_take_profit(), 3)
                precio_val = round(row["Close"], 2)
                todas_las_senales.append({"Ticker": ticker, "Estrategia": nombre_est, "Fecha": idx, "Precio": precio_val, "TP Limit": tp_val})

    except Exception as e:
        continue

df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    print(f"\n📊 TOTAL DE SEÑALES ENCONTRADAS: {len(df_final)}")
    ultimas_senales = df_final.tail(3) # Cogemos las 3 últimas para que el mensaje no sea gigante

    mensaje_telegram = "🎯 *¡AVISO SENCILLO DE INVERSIÓN!* 🎯\n\n"
    for _, r in ultimas_senales.iterrows():
        t = r['Ticker']
        nombre_largo = nombres_amigables.get(t, t)
        est = r['Estrategia']
        explicacion = explicaciones_estrategias.get(est, "Movimiento interesante detectado.")

        mensaje_telegram += f"🏢 *Empresa:* {nombre_largo}\n" \
                            f"📈 *Qué pasó:* {explicacion}\n" \
                            f"📅 *Cuándo:* {r['Fecha']}\n" \
                            f"💵 *Precio actual:* `${r['Precio']}`\n" \
                            f"🎯 *Objetivo de ganancia (TP):* `${r['TP Limit']}`\n\n" \
                            f"-----------------------------------\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Alerta súper explicada enviada a Telegram con éxito!")
else:
    print("No se encontraron señales activas.")
print("==========================================================================")

In [ ]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Nombres amigables para las empresas
nombres_amigables = {
    "SPY": "S&P 500 (SPY)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "DIA": "Dow Jones (DIA)",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "GOOG": "Google",
    "MSFT": "Microsoft",
    "NFLX": "Netflix",
    "CMG": "Chipotle",
    "WMT": "Walmart",
    "COST": "Costco",
    "MCD": "McDonald's",
    "NKE": "Nike",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "WFC": "Wells Fargo",
    "C": "Citigroup",
    "JNJ": "Johnson & Johnson",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "F": "Ford"
}

def enviar_alerta_telegram(mensaje):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = list(nombres_amigables.keys())

print("==========================================================================")
print("     MATRIZ MAESTRA - FORMATO SÚPER SENCILLO PARA FRAN                     ")
print("==========================================================================")

todas_las_senales = []

for ticker in universo_activos:
    try:
        df = yf.download(ticker, period="60d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # Estrategias
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"]) & (df["SMA_100"] > df["SMA_200"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.004)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        max_dec = (df["High"].shift(1) < df["High"].shift(2)) & (df["High"].shift(2) < df["High"].shift(3))
        s_est1 = max_dec & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1)) & (df["Volume"] > df["Volume"].rolling(window=20).mean())

        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_est2 = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        cuerpo = abs(df["Close"] - df["Open"])
        sombra_inf = df[["Open", "Close"]].min(axis=1) - df["Low"]
        sombra_sup = df["High"] - df[["Open", "Close"]].max(axis=1)
        es_hammer = (cuerpo > 0) & (sombra_inf >= (2 * cuerpo)) & (sombra_sup <= (0.5 * cuerpo))
        s_hammer = (df["Close"] < df["Close"].shift(5)) & es_hammer.shift(1) & (df["High"] > df["High"].shift(1))

        estrategias_activas = [
            (s_call, "Pullback SMA40 (CALL)"),
            (s_est1, "Estrategia 1 (Piso Fuerte)"),
            (s_est2, "Estrategia 2 (Ruptura Rango)"),
            (s_hammer, "Estrategia 5 (Hammer)")
        ]

        for condicion, nombre_est in estrategias_activas:
            for idx, row in df[condicion].iterrows():
                precio_val = round(row["Close"], 2)
                todas_las_senales.append({"Ticker": ticker, "Estrategia": nombre_est, "Fecha": idx, "Precio": precio_val})

    except Exception as e:
        continue

df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    print(f"\n📊 TOTAL DE SEÑALES ENCONTRADAS: {len(df_final)}")
    ultimas_senales = df_final.tail(3) # Cogemos las 3 últimas para que sea cómodo de leer

    mensaje_telegram = "🚨 *¡NUEVA ALERTA PARA TI!* 🚨\n\n"
    for _, r in ultimas_senales.iterrows():
        nombre_empresa = nombres_amigables.get(r['Ticker'], r['Ticker'])
        estrategia = r['Estrategia']
        fecha = r['Fecha']
        precio = r['Precio']

        mensaje_telegram += f"Fran, hemos detectado que puedes invertir con la estrategia *{estrategia}* en *{nombre_empresa}*, ¿vale? Y puedes comprar call a partir de esta vela del *{fecha}* (Precio: `${precio}`).\n\n" \
                            f"-----------------------------------\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Alerta clara y sencilla enviada a Telegram!")
else:
    print("No se encontraron señales activas.")
print("==========================================================================")

In [ ]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Nombres amigables para las empresas y ETFs
nombres_amigables = {
    "SPY": "S&P 500 (SPY)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "DIA": "Dow Jones (DIA)",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "GOOG": "Google",
    "MSFT": "Microsoft",
    "NFLX": "Netflix",
    "CMG": "Chipotle",
    "WMT": "Walmart",
    "COST": "Costco",
    "MCD": "McDonald's",
    "NKE": "Nike",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "WFC": "Wells Fargo",
    "C": "Citigroup",
    "JNJ": "Johnson & Johnson",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "F": "Ford"
}

def enviar_alerta_telegram(mensaje):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = list(nombres_amigables.keys())

print("==========================================================================")
print("     MONITOR EN TIEMPO REAL - CALL / PUT & VELAS HORA A HORA              ")
print("==========================================================================")

alertas_para_enviar = []

for ticker in universo_activos:
    try:
        # Descargamos datos recientes de gráficos de 1 hora
        df = yf.download(ticker, period="5d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Analizamos la última vela cerrada
        ultima_vela = df.iloc[-1]
        hora_vela = ultima_vela.name.strftime('%H:%M')
        fecha_vela = ultima_vela.name.strftime('%Y-%m-%d')

        open_price = ultima_vela["Open"]
        close_price = ultima_vela["Close"]
        precio_actual = round(close_price, 2)

        # Determinamos si es Alcista (Verde -> Call) o Bajista (Roja -> Put)
        if close_price > open_price:
            tipo_operacion = "CALL 🟢 (Alcista / Verde)"
            instruccion = "puedes buscar una entrada en compra (Call)"
        else:
            tipo_operacion = "PUT 🔴 (Bajista / Roja)"
            instruccion = "puedes buscar una entrada en venta (Put)"

        nombre_empresa = nombres_amigables.get(ticker, ticker)

        alertas_para_enviar.append({
            "Empresa": nombre_empresa,
            "Hora": hora_vela,
            "Fecha": fecha_vela,
            "Operacion": tipo_operacion,
            "Instruccion": instruccion,
            "Precio": precio_actual
        })

    except Exception as e:
        continue

if alertas_para_enviar:
    # Seleccionamos algunas de las principales para no saturar el chat
    mensaje_telegram = "🔔 *REPORTE DE APERTURA Y VELAS* 🔔\n\n"
    mensaje_telegram += "Fran, la bolsa abre a las 9:30 y aquí tienes el escaneo de las últimas velas:\n\n"

    # Tomamos 4 activos de muestra para que el mensaje sea limpio y directo
    for item in alertas_para_enviar[:4]:
        mensaje_telegram += f"📌 *{item['Empresa']}* ({item['Fecha']} a las {item['Hora']}):\n" \
                            f"La vela fue de tipo *{item['Operacion']}* a ${item['Precio']}.\n" \
                            f"➡️ Fran, {item['Instruccion']}.\n\n" \
                            f"-----------------------------------\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Reporte de velas y Call/Put enviado a Telegram con éxito!")
else:
    print("No se pudieron generar alertas en este momento.")
print("==========================================================================")

In [ ]:
import pandas as pd
import yfinance as yf
import warnings
import requests

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Nombres amigables para las empresas y ETFs
nombres_amigables = {
    "SPY": "S&P 500 (SPY)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "DIA": "Dow Jones (DIA)",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "GOOG": "Google",
    "MSFT": "Microsoft",
    "NFLX": "Netflix",
    "CMG": "Chipotle",
    "WMT": "Walmart",
    "COST": "Costco",
    "MCD": "McDonald's",
    "NKE": "Nike",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "WFC": "Wells Fargo",
    "C": "Citigroup",
    "JNJ": "Johnson & Johnson",
    "KO": "Coca-Cola",
    "PEP": "PepsiCo",
    "F": "Ford"
}

def enviar_alerta_telegram(mensaje):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": mensaje,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        print(f"Error al enviar Telegram: {e}")

universo_activos = list(nombres_amigables.keys())

print("==========================================================================")
print("     MATRIZ INTELIGENTE - DETECCIÓN AUTOMÁTICA DE CALL / PUT               ")
print("==========================================================================")

todas_las_senales = []

for ticker in universo_activos:
    try:
        # Descargamos datos de gráficos de 1 hora
        df = yf.download(ticker, period="30d", interval="60m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')

        # Medias Móviles Base
        df["SMA_20"] = df["Close"].rolling(window=20).mean()
        df["SMA_40"] = df["Close"].rolling(window=40).mean()
        df["SMA_100"] = df["Close"].rolling(window=100).mean()
        df["SMA_200"] = df["Close"].rolling(window=200).mean()

        # --- ESTRATEGIAS ALCISTAS (CALL) ---
        tendencia_alcista = (df["SMA_20"] > df["SMA_40"]) & (df["SMA_40"] > df["SMA_100"])
        distancia_alcista = abs(df["Low"] - df["SMA_40"]) / df["SMA_40"]
        pullback_alcista = tendencia_alcista & (distancia_alcista <= 0.005)
        s_call = pullback_alcista.shift(1) & (df["Close"] > df["Open"]) & (df["High"] > df["High"].shift(1))

        max_20 = df["High"].rolling(window=20).max().shift(1)
        s_ruptura_call = (df["Close"] > max_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] > df["Open"])

        # --- ESTRATEGIAS BAJISTAS (PUT) ---
        tendencia_bajista = (df["SMA_20"] < df["SMA_40"]) & (df["SMA_40"] < df["SMA_100"])
        min_20 = df["Low"].rolling(window=20).min().shift(1)
        s_ruptura_put = (df["Close"] < min_20) & (df["Volume"] > (df["Volume"].rolling(window=20).mean() * 1.2)) & (df["Close"] < df["Open"])

        # Evaluamos si alguna condición se cumple en el DataFrame
        estrategias_a_evaluar = [
            (s_call, "Pullback SMA40", "CALL 🟢 (Compra alcista)"),
            (s_ruptura_call, "Ruptura de Rango", "CALL 🟢 (Ruptura al alza)"),
            (s_ruptura_put, "Ruptura de Soporte", "PUT 🔴 (Caída bajista)")
        ]

        for condicion, nombre_est, tipo_op in estrategias_a_evaluar:
            for idx, row in df[condicion].iterrows():
                precio_val = round(row["Close"], 2)
                fecha_str = idx.strftime('%Y-%m-%d %H:%M')
                todas_las_senales.append({
                    "Ticker": ticker,
                    "Estrategia": nombre_est,
                    "Operacion": tipo_op,
                    "Fecha": fecha_str,
                    "Precio": precio_val
                })

    except Exception as e:
        continue

df_final = pd.DataFrame(todas_las_senales)
if not df_final.empty:
    print(f"\n📊 TOTAL DE SEÑALES ENCONTRADAS: {len(df_final)}")
    ultimas_senales = df_final.tail(3) # Las 3 últimas detectadas

    mensaje_telegram = "🚨 *MATRIZ DE OPERACIONES (CALL / PUT)* 🚨\n\n"
    mensaje_telegram += "Fran, la bolsa abre a las 9:30 y el sistema ha analizado tus estrategias:\n\n"

    for _, r in ultimas_senales.iterrows():
        nombre_empresa = nombres_amigables.get(r['Ticker'], r['Ticker'])

        mensaje_telegram += f"Fran, hemos detectado la estrategia *{r['Estrategia']}* en *{nombre_empresa}*.\n" \
                            f"➡️ Dirección recomendada: *{r['Operacion']}*.\n" \
                            f"📅 Vela del: {r['Fecha']} (Precio: `${r['Precio']}`).\n\n" \
                            f"-----------------------------------\n\n"

    respuesta = enviar_alerta_telegram(mensaje_telegram)
    print("📲 ¡Alerta de Call/Put inteligente enviada a Telegram con éxito!")
else:
    print("No se encontraron señales de estrategia activas en este momento.")
print("==========================================================================")

In [ ]:
import io
import warnings
import matplotlib.pyplot as plt
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Nombres amigables para las empresas y ETFs
nombres_amigables = {
    "SPY": "S&P 500 (SPY)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "MSFT": "Microsoft",
    "F": "Ford",
}


def enviar_foto_telegram(foto_bytes, caption):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto"
  files = {"photo": ("chart.png", foto_bytes, "image/png")}
  data = {"chat_id": CHAT_ID, "caption": caption, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, data=data, files=files)
    return response.json()
  except Exception as e:
    print(f"Error al enviar imagen a Telegram: {e}")


print("==========================================================================")
print("     MONITOR CON GRÁFICOS 16:9 Y FILTRO DE APERTURA (10:00 AM)             ")
print("==========================================================================")

senales_encontradas = 0

for ticker, nombre_empresa in nombres_amigables.items():
  try:
    # Descargamos datos de 30 minutos para ver la vela de 9:30 y la de 10:00
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    df.index = df.index.tz_convert("America/New_York")

    # Medias Móviles para la tendencia
    df["SMA_20"] = df["Close"].rolling(window=20).mean()
    df["SMA_40"] = df["Close"].rolling(window=40).mean()

    # Tomamos la última vela cerrada
    ultima_vela = df.iloc[-1]
    hora_vela = ultima_vela.name.strftime("%H:%M")
    fecha_vela = ultima_vela.name.strftime("%Y-%m-%d")

    # REGLA 1: Ignorar la vela de apertura de las 09:30
    if hora_vela == "09:30":
      continue

    # REGLA 2: A partir de las 10:00, comprobar si es alcista y cumple tendencia
    tendencia_alcista = (
        ultima_vela["Close"] > ultima_vela["SMA_20"]
    ) and (ultima_vela["SMA_20"] > ultima_vela["SMA_40"])
    es_verde = ultima_vela["Close"] > ultima_vela["Open"]

    if hora_vela >= "10:00" and es_verde and tendencia_alcista:
      precio_actual = round(ultima_vela["Close"], 2)

      # --- GENERAR GRÁFICO EN 16:9 ---
      plt.figure(
          figsize=(12, 6.75)
      )  # Proporción 16:9 exacta para tus preferencias
      ultimos_dias = df.tail(30)
      plt.plot(
          ultimos_dias.index,
          ultimos_dias["Close"],
          label="Precio",
          color="#1f77b4",
          linewidth=2,
      )
      plt.plot(
          ultimos_dias.index,
          ultimos_dias["SMA_20"],
          label="Media 20",
          color="#ff7f0e",
          linestyle="--",
      )

      # Marcar el punto de entrada exacto
      plt.scatter(
          [ultima_vela.name],
          [ultima_vela["Close"]],
          color="green",
          s=150,
          zorder=5,
          label="Entrada CALL",
      )

      plt.title(
          f"Estrategia CALL - {nombre_empresa} ({fecha_vela} {hora_vela})",
          fontsize=14,
          fontweight="bold",
      )
      plt.xlabel("Hora / Fecha", fontsize=10)
      plt.ylabel("Precio ($)", fontsize=10)
      plt.legend(loc="upper left")
      plt.grid(True, linestyle=":", alpha=0.6)
      plt.tight_layout()

      # Guardar gráfico en memoria RAM sin necesidad de guardarlo en disco duro
      buf = io.BytesIO()
      plt.savefig(buf, format="png", dpi=150)
      buf.seek(0)
      plt.close()

      # Mensaje para Telegram
      mensaje = (
          f"🚨 *¡SEÑAL DE CALL CONFIRMADA!* 🚨\n\n"
          f"Fran, ya pasó la apertura de las 9:30. La vela de las *{hora_vela}* en *{nombre_empresa}* ha cerrado verde y estamos en tendencia alcista.\n\n"
          f"➡️ *Acción:* Puedes comprar un *CALL* a partir de ${precio_actual}.\n"
          f"📅 *Fecha:* {fecha_vela}\n\n"
          f"Te adjunto el gráfico exacto del momento de entrada."
      )

      enviar_foto_telegram(buf.read(), mensaje)
      senales_encontradas += 1
      print(
          f"✅ Alerta con gráfico 16:9 enviada para {nombre_empresa} a las"
          f" {hora_vela}"
      )

  except Exception as e:
    continue

print(f"\n📊 Total de gráficos con señales enviados: {senales_encontradas}")
print("==========================================================================")

In [ ]:
!pip install mplfinance -q

In [ ]:
import io
import warnings
import matplotlib.pyplot as plt
import mplfinance as mpf
import pandas as pd
import requests
import yfinance as yf

warnings.filterwarnings('ignore')

TELEGRAM_TOKEN = "8556809936:AAFaziJLF1BOgnyXSBfJgt6SJ2asida9daE"
CHAT_ID = "8642681599"

def enviar_foto_telegram(foto_bytes, caption):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto"
    files = {"photo": ("chart.png", foto_bytes, "image/png")}
    data = {"chat_id": CHAT_ID, "caption": caption, "parse_mode": "Markdown"}
    try:
        response = requests.post(url, data=data, files=files)
        return response.json()
    except Exception as e:
        print(f"Error: {e}")

nombres_amigables = {"SPY": "S&P 500", "AAPL": "Apple", "F": "Ford"}

for ticker, nombre in nombres_amigables.items():
    try:
        df = yf.download(ticker, period="5d", interval="30m", progress=False, auto_adjust=False)
        if df.empty: continue
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df.index = df.index.tz_convert('America/New_York')
        ultima_vela = df.iloc[-1]

        if ultima_vela.name.strftime('%H:%M') == "09:30":
            continue

        fig, axes = mpf.plot(df.tail(20), type='candle', style='yahoo', returnfig=True, figsize=(12, 6.75))

        buf = io.BytesIO()
        fig.savefig(buf, format='png', dpi=150)
        buf.seek(0)
        plt.close(fig)

        mensaje = f"🚨 *¡SEÑAL CONFIRMADA!* 🚨\nFran, en *{nombre}* el mercado dio entrada en la última vela. Te adjunto el gráfico de velas en tiempo real."

        enviar_foto_telegram(buf.read(), mensaje)
        print(f"✅ Alerta con velas enviada para {nombre}")
    except Exception as e:
        continue

In [ ]:
import io
import warnings
import matplotlib.pyplot as plt
import mplfinance as mpf
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos basada en tus capturas
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_foto_telegram(foto_bytes, caption):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto"
  files = {"photo": ("chart.png", foto_bytes, "image/png")}
  data = {"chat_id": CHAT_ID, "caption": caption, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, data=data, files=files)
    return response.json()
  except Exception as e:
    print(f"Error al enviar imagen a Telegram: {e}")


print("==========================================================================")
print("     MONITOR TOTAL DE ACTIVOS - FILTRO 10:00 AM Y VELAS REALES            ")
print("==========================================================================")

reporte_general = (
    "📊 *REPORTE GENERAL DE TUS ACTIVOS* 📊\n\n"
    "Fran, la bolsa abrió y ya pasó el filtro de las 9:30. Aquí tienes el análisis de toda tu lista:\n\n"
)

activos_analizados = 0

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos de 30 minutos
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    df.index = df.index.tz_convert("America/New_York")
    ultima_vela = df.iloc[-1]
    hora_vela = ultima_vela.name.strftime("%H:%M")

    # REGLA: Si es la vela de las 09:30, la ignoramos
    if hora_vela == "09:30":
      reporte_general += (
          f"📌 *{nombre}*: Esperando cierre de vela (última a las 09:30, sin"
          " operar).\n\n"
      )
      continue

    # Determinamos tendencia y dirección (Call / Put)
    open_p = ultima_vela["Open"]
    close_p = ultima_vela["Close"]
    precio_actual = round(close_p, 2)

    if close_p > open_p:
      direccion = "CALL 🟢 (Alcista / Vela Verde)"
    else:
      direccion = "PUT 🔴 (Bajista / Vela Roja)"

    reporte_general += (
        f"📌 *{nombre}* ({hora_vela}):\n➡️ Dirección: *{direccion}* a"
        f" `${precio_actual}`\n\n"
    )

    # Generamos el gráfico de velas para este activo
    fig, axes = mpf.plot(
        df.tail(15),
        type="candle",
        style="yahoo",
        returnfig=True,
        figsize=(12, 6.75),
    )

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150)
    buf.seek(0)
    plt.close(fig)

    # Enviamos la gráfica individual con su info a Telegram
    caption_activo = (
        f"📈 *{nombre}* - Vela de las {hora_vela}\nSugerencia: Operar"
        f" *{direccion}* a ${precio_actual}"
    )
    enviar_foto_telegram(buf.read(), caption_activo)
    activos_analizados += 1

  except Exception as e:
    continue

# Enviamos el reporte resumen completo al final
url_msg = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
requests.post(
    url_msg,
    json={"chat_id": CHAT_ID, "text": reporte_general, "parse_mode": "Markdown"},
)

print(
    f"\n✅ ¡Reporte completo enviado! Total de gráficos analizados:"
    f" {activos_analizados}"
)
print("==========================================================================")

In [ ]:
import io
import warnings
import matplotlib.pyplot as plt
import mplfinance as mpf
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_foto_telegram(foto_bytes, caption):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto"
  files = {"photo": ("chart.png", foto_bytes, "image/png")}
  data = {"chat_id": CHAT_ID, "caption": caption, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, data=data, files=files)
    return response.json()
  except Exception as e:
    print(f"Error al enviar imagen a Telegram: {e}")


print("==========================================================================")
print("     MONITOR TOTAL DE ACTIVOS - HORARIO ESTRICTO DE NUEVA YORK             ")
print("==========================================================================")

reporte_general = (
    "📊 *REPORTE GENERAL (HORARIO DE NUEVA YORK)* 📊\n\n"
    "Fran, aquí tienes el análisis de tus activos basado en la hora de apertura americana (NY):\n\n"
)

activos_analizados = 0

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos de 30 minutos
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Forzamos la conversión estricta al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")
    ultima_vela = df.iloc[-1]
    hora_vela = ultima_vela.name.strftime("%H:%M")

    # REGLA ESTRICTA: Si es la vela de apertura de las 09:30 (Hora NY), se ignora
    if hora_vela == "09:30":
      reporte_general += (
          f"📌 *{nombre}*: Esperando cierre (última vela a las 09:30 NY, sin"
          " operar).\n\n"
      )
      continue

    open_p = ultima_vela["Open"]
    close_p = ultima_vela["Close"]
    precio_actual = round(close_p, 2)

    if close_p > open_p:
      direccion = "CALL 🟢 (Alcista / Vela Verde)"
    else:
      direccion = "PUT 🔴 (Bajista / Vela Roja)"

    reporte_general += (
        f"📌 *{nombre}* ({hora_vela} NY):\n➡️ Dirección: *{direccion}* a"
        f" `${precio_actual}`\n\n"
    )

    # Gráfico de velas
    fig, axes = mpf.plot(
        df.tail(15),
        type="candle",
        style="yahoo",
        returnfig=True,
        figsize=(12, 6.75),
    )

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150)
    buf.seek(0)
    plt.close(fig)

    caption_activo = (
        f"📈 *{nombre}* - Vela de las {hora_vela} (Hora NY)\nSugerencia:"
        f" Operar *{direccion}* a ${precio_actual}"
    )
    enviar_foto_telegram(buf.read(), caption_activo)
    activos_analizados += 1

  except Exception as e:
    continue

url_msg = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
requests.post(
    url_msg,
    json={"chat_id": CHAT_ID, "text": reporte_general, "parse_mode": "Markdown"},
)

print(
    f"\n✅ ¡Reporte en horario de Nueva York enviado! Gráficos:"
    f" {activos_analizados}"
)
print("==========================================================================")

In [ ]:
import warnings
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_mensaje_telegram(mensaje):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
  payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, json=payload)
    return response.json()
  except Exception as e:
    print(f"Error al enviar mensaje a Telegram: {e}")


print("==========================================================================")
print("     REPORTE GENERAL ÚNICO - ANÁLISIS DE LA SEGUNDA VELA (10:00 NY)        ")
print("==========================================================================")

reporte_general = (
    "📊 *REPORTE GENERAL DE TUS ACTIVOS* 📊\n\n"
    "Fran, aquí tienes el resumen de cómo ha cerrado la *segunda vela del día (10:00 - 10:30 NY)* para cada activo:\n\n"
)

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos recientes de 30 minutos
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Convertimos al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")

    # Buscamos la vela correspondiente a las 10:00 (la segunda vela, ignorando las 09:30)
    # Filtramos las velas del día actual o la última sesión disponible
    velas_hoy = df[df.index.date == df.index[-1].date()]

    # Verificamos si existe la vela de las 10:00
    vela_1000 = None
    for idx, row in velas_hoy.iterrows():
      if idx.strftime("%H:%M") == "10:00":
        vela_1000 = row
        break

    if vela_1000 is not None:
      open_p = vela_1000["Open"]
      close_p = vela_1000["Close"]
      precio = round(close_p, 2)

      if close_p > open_p:
        estado = "🟢 Positiva / Verde (¡Ideal para CALL si hay tendencia!)"
      else:
        estado = "🔴 Negativa / Roja"

      reporte_general += (
          f"📌 *{nombre}*:\n"
          f"   • 2ª Vela (10:00 NY): *{estado}*\n"
          f"   • Precio de cierre: `${precio}`\n\n"
      )
    else:
      reporte_general += (
          f"📌 *{nombre}*:\n   • Sin datos suficientes para la vela de las"
          " 10:00 NY.\n\n"
      )

  except Exception as e:
    continue

# Enviamos únicamente el reporte general consolidado a Telegram
enviar_mensaje_telegram(reporte_general)

print(
    "\n✅ ¡Reporte general único enviado con éxito a Telegram (sin spam"
    " individual)!"
)
print("==========================================================================")

In [ ]:
import warnings
import numpy as np
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_mensaje_telegram(mensaje):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
  payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, json=payload)
    return response.json()
  except Exception as e:
    print(f"Error al enviar mensaje a Telegram: {e}")


print("==========================================================================")
print("     REPORTE INTELIGENTE: CANALES Y RECOMENDACIONES TÁCTICAS (NY)         ")
print("==========================================================================")

reporte_general = (
    "📊 *REPORTE TÁCTICO DE CANALES Y VELAS (NY)* 📊\n\n"
    "Fran, aquí tienes el análisis automatizado de canales (alcista/bajista) y las recomendaciones para operar:\n\n"
)

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos históricos recientes de 30m para calcular canales
    df = yf.download(
        ticker, period="10d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty or len(df) < 20:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Convertimos al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")

    # --- DETECCIÓN DE CANAL (Tendencia basada en los últimos periodos) ---
    # Usamos una regresión lineal simple o la pendiente de los cierres recientes (últimas 10 velas)
    cierres_recientes = df["Close"].tail(10).values
    x = np.arange(len(cierres_recientes))
    slope, _ = np.polyfit(x, cierres_recientes, 1)

    # Estimamos cuántas velas lleva en esta dirección (aproximando días/velas)
    fuerza_tendencia = "Canal Alcista 📈" if slope > 0 else "Canal Bajista 📉"
    duracion_velas = len(cierres_recientes)

    # Identificamos la segunda vela del día actual (10:00 NY)
    velas_hoy = df[df.index.date == df.index[-1].date()]
    vela_1000 = None
    for idx, row in velas_hoy.iterrows():
      if idx.strftime("%H:%M") == "10:00":
        vela_1000 = row
        break

    if vela_1000 is not None:
      open_p = vela_1000["Open"]
      close_p = vela_1000["Close"]
      precio = round(close_p, 2)
      es_verde = close_p > open_p

      # Lógica de recomendación personalizada estilo trading
      if slope < 0:
        # Canal Bajista
        if not es_verde:
          consejo = (
              "🔴 *Canal Bajista detectado*. Vela roja confirmada.\n   👉"
              " *Recomendación*: No recomiendo comprar CALL. *Ideal comprar PUT*."
          )
        else:
          consejo = (
              "⚠️ *Canal Bajista*, pero esta vela amagó verde.\n   👉"
              " *Recomendación*: Precaución con los CALLs, esperar confirmación"
              " bajista para PUT."
          )
      else:
        # Canal Alcista
        if es_verde:
          consejo = (
              "🟢 *Canal Alcista detectado*. Vela verde confirmada.\n   👉"
              " *Recomendación*: No recomiendo comprar PUT. *Ideal comprar CALL*."
          )
        else:
          consejo = (
              "⚠️ *Canal Alcista*, pero esta vela cerró roja.\n   👉"
              " *Recomendación*: Cuidado, posible retroceso en zona alta."
          )

      reporte_general += (
          f"📌 *{nombre}*:\n"
          f"   • Tendencia: *{fuerza_tendencia}*\n"
          f"   • 2ª Vela (10:00 NY): "
          f"{'🟢 Verde (Positiva)' if es_verde else '🔴 Roja (Negativa'})\n"
          f"   • Precio: `${precio}`\n"
          f"   {consejo}\n\n"
      )
    else:
      reporte_general += (
          f"📌 *{nombre}*:\n   • Tendencia: {fuerza_tendencia}\n   • Sin datos"
          " suficientes para la vela de las 10:00 NY.\n\n"
      )

  except Exception as e:
    continue

# Enviamos el reporte general inteligente a Telegram
enviar_mensaje_telegram(reporte_general)

print(
    "\n✅ ¡Reporte táctico de canales y recomendaciones enviado con éxito a"
    " Telegram!"
)
print("==========================================================================")

In [ ]:
import warnings
import numpy as np
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_mensaje_telegram(mensaje):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
  payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, json=payload)
    return response.json()
  except Exception as e:
    print(f"Error al enviar mensaje a Telegram: {e}")


print("==========================================================================")
print("     REPORTE INTELIGENTE DE CIERRE Y PERSPECTIVAS FUTURAS (NY)            ")
print("==========================================================================")

reporte_general = (
    f"🔔 *REPORTE DE CIERRE DE MERCADO Y PERSPECTIVAS* 🔔\n\n"
    f"Hola *Franz*. Aquí tienes el análisis global del comportamiento de tus activos al cierre de la sesión y las proyecciones para futuras inversiones:\n\n"
    f"━━━━━━━━━━━━━━━━━━━━━━\n"
    f"📈 *ANÁLISIS DE LA SESIÓN Y TENDENCIAS*:\n\n"
)

resumen_proyecciones = (
    f"━━━━━━━━━━━━━━━━━━━━━━\n"
    f"🎯 *PUNTO DE VISTA PARA FUTURAS INVERSIONES (CALL / PUT)*:\n\n"
)

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos históricos recientes de 30m para evaluar canal y cierre del día
    df = yf.download(
        ticker, period="10d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty or len(df) < 20:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Convertimos al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")

    # Tendencia general (Canal)
    cierres_recientes = df["Close"].tail(10).values
    x = np.arange(len(cierres_recientes))
    slope, _ = np.polyfit(x, cierres_recientes, 1)

    tendencia = "Canal Alcista 📈" if slope > 0 else "Canal Bajista 📉"

    # Evaluamos la última vela del día (cierre)
    ultima_vela = df.iloc[-1]
    open_cierre = ultima_vela["Open"]
    close_cierre = ultima_vela["Close"]
    precio_cierre = round(close_cierre, 2)
    cierre_verde = close_cierre > open_cierre

    # Añadimos al reporte de sesión
    reporte_general += (
        f"📌 *{nombre}*:\n"
        f"   • Cierre: `${precio_cierre}` ({'Verde 🟢' if cierre_verde else 'Roja 🔴'})\n"
        f"   • Estructura: *{tendencia}*\n\n"
    )

    # Generamos la perspectiva para futuras inversiones
    if slope < 0:
      # Si está en bajista
      perspectiva = (
          f"🔸 *{nombre}* (Bajista): El activo mantiene presión vendedora. "
          f"Evitar buscar CALLs precipitados. *Vigilar la primera vela roja en próxima sesión para posibles entradas en PUT*.\n\n"
      )
    else:
      # Si está en alcista
      perspectiva = (
          f"🔸 *{nombre}* (Alcista): Estructura favorable al alza. "
          f"Evitar compras en PUT contra tendencia. *Atentos a correcciones para buscar oportunidades en CALL*.\n\n"
      )

    resumen_proyecciones += perspectiva

  except Exception as e:
    continue

# Unimos ambas partes en un solo mensaje estructurado
mensaje_final = reporte_general + resumen_proyecciones

# Enviamos el reporte general consolidado de cierre a Telegram
enviar_mensaje_telegram(mensaje_final)

print(
    "\n✅ ¡Reporte global de cierre y proyecciones enviado correctamente a"
    " Telegram, Franz!"
)
print("==========================================================================")

In [ ]:
import warnings
import numpy as np
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_alerta_telegram(mensaje):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
  payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, json=payload)
    return response.json()
  except Exception as e:
    print(f"Error al enviar Telegram: {e}")


print("==========================================================================")
print("     MONITOR TÁCTICO EN TIEMPO REAL - ALERTAS DE ENTRADA (NY)             ")
print("==========================================================================")

alertas_enviadas = 0

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos recientes de 30m
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty or len(df) < 20:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Convertimos estrictamente al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")

    # Analizamos la última vela cerrada
    ultima_vela = df.iloc[-1]
    hora_vela = ultima_vela.name.strftime("%H:%M")

    # REGLA DE ORO DE FRANZ: Ignoramos la vela de apertura de las 09:30 a 10:00
    if hora_vela == "09:30":
      continue

    # Calculamos el canal (tendencia de las últimas 10 velas)
    cierres_recientes = df["Close"].tail(10).values
    x = np.arange(len(cierres_recientes))
    slope, _ = np.polyfit(x, cierres_recientes, 1)
    en_canal_bajista = slope < 0

    open_p = ultima_vela["Open"]
    close_p = ultima_vela["Close"]
    precio_actual = round(close_p, 2)
    es_vela_verde = close_p > open_p

    # DISPARADOR DE ESTRATEGIA EN TIEMPO REAL
    # Si estamos a las 10:00 o más tarde, evaluamos tus reglas exactas:
    if hora_vela >= "10:00":
      if en_canal_bajista and not es_vela_verde:
        # Canal bajista + vela roja que cierra = ¡Oportunidad de PUT!
        alerta = (
            f"🚨 *¡ALERTA TÁCTICA PARA FRANZ!* 🚨\n\n"
            f"⚡ *Activo*: *{nombre}*\n"
            f"⏰ *Hora NY*: {hora_vela} (Vela cerrada)\n"
            f"📉 *Estructura*: Canal bajista activo.\n\n"
            f"👉 *Franz, corre*: La vela acaba de cerrar *ROJA* a `${precio_actual}` dentro del canal bajista.\n"
            f"❌ *No compres CALL*.\n"
            f"🎯 *Acción sugerida*: Es el momento idóneo para buscar una entrada en **PUT**."
        )
        enviar_alerta_telegram(alerta)
        alertas_enviadas += 1

      elif not en_canal_bajista and es_vela_verde:
        # Canal alcista + vela verde que cierra = ¡Oportunidad de CALL!
        alerta = (
            f"🚨 *¡ALERTA TÁCTICA PARA FRANZ!* 🚨\n\n"
            f"⚡ *Activo*: *{nombre}*\n"
            f"⏰ *Hora NY*: {hora_vela} (Vela cerrada)\n"
            f"📈 *Estructura*: Canal alcista activo.\n\n"
            f"👉 *Franz, corre*: La vela acaba de cerrar *VERDE* a `${precio_actual}` en tendencia alcista.\n"
            f"❌ *No compres PUT*.\n"
            f"🎯 *Acción sugerida*: Es el momento idóneo para buscar una entrada en **CALL**."
        )
        enviar_alerta_telegram(alerta)
        alertas_enviadas += 1

  except Exception as e:
    continue

print(
    f"\n✅ Análisis completado, Franz. Alertas tácticas enviadas:"
    f" {alertas_enviadas}"
)
print("==========================================================================")

In [ ]:
import warnings
import numpy as np
import pandas as pd
import requests
import yfinance as yf

# Silenciar advertencias
warnings.filterwarnings('ignore')

# --- CONFIGURACIÓN DE TELEGRAM ---
p1 = "8556809936:AAFaziJLF1BOgnyXSBfJgt6S"
p2 = "J2asida9daE"
TELEGRAM_TOKEN = p1 + p2
CHAT_ID = "8642681599"

# Lista completa de tus activos
activos_frances = {
    "SPY": "S&P 500 ETF (SPY)",
    "GLD": "SPDR Gold Shares (GLD)",
    "QQQ": "Invesco QQQ (Tecnología)",
    "META": "Meta Platforms (Facebook)",
    "NVDA": "NVIDIA Corporation",
    "AAPL": "Apple",
    "AMZN": "Amazon",
    "NFLX": "Netflix",
    "TSLA": "Tesla",
    "BAC": "Bank of America",
    "CMG": "Chipotle Mexican Grill",
    "SLV": "iShares Silver Trust (Plata)",
    "USO": "United States Oil Fund",
    "FB": "ProShares S&P 500",
}


def enviar_alerta_telegram(mensaje):
  url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
  payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
  try:
    response = requests.post(url, json=payload)
    return response.json()
  except Exception as e:
    print(f"Error al enviar Telegram: {e}")


print("==========================================================================")
print("     MONITOR TÁCTICO DAY TRADING - ANÁLISIS AUTOMATIZADO (NY)             ")
print("==========================================================================")

reporte_general = (
    f"🤖 *REPORTE AUTOMATIZADO DE DAY TRADING* 🤖\n\n"
    f"Hola *Franz*. Aquí tienes el escaneo en tiempo real de tus activos con las señales de opciones (Call/Put) basadas en tus estrategias:\n\n"
)

senales_encontradas = 0

for ticker, nombre in activos_frances.items():
  try:
    # Descargamos datos recientes de 30m para day trading
    df = yf.download(
        ticker, period="5d", interval="30m", progress=False, auto_adjust=False
    )
    if df.empty or len(df) < 20:
      continue
    if isinstance(df.columns, pd.MultiIndex):
      df.columns = df.columns.get_level_values(0)

    # Convertimos estrictamente al horario de Nueva York
    df.index = df.index.tz_convert("America/New_York")

    # Analizamos la última vela cerrada
    ultima_vela = df.iloc[-1]
    hora_vela = ultima_vela.name.strftime("%H:%M")

    # Evitamos la vela de apertura inicial de las 09:30
    if hora_vela == "09:30":
      continue

    # Detección del canal o tendencia (últimas 10 velas)
    cierres_recientes = df["Close"].tail(10).values
    x = np.arange(len(cierres_recientes))
    slope, _ = np.polyfit(x, cierres_recientes, 1)
    en_canal_bajista = slope < 0

    open_p = ultima_vela["Open"]
    close_p = ultima_vela["Close"]
    precio_actual = round(close_p, 2)
    es_vela_verde = close_p > open_p

    # Lógica automatizada para Day Trading (Operaciones en corto / intradía)
    if en_canal_bajista:
      if not es_vela_verde:
        estrategia = (
            "📉 *Señal Bajista Confirmada*:\n"
            "   • Canal bajista activo y vela cerrada *Roja*.\n"
            "   👉 *Estrategia Day Trading*: Evitar CALL. *Oportunidad ideal para PUT* a"
            f" `${precio_actual}`."
        )
        senales_encontradas += 1
      else:
        estrategia = (
            "⚠️ *Atención Bajista*:\n"
            "   • Canal bajista pero la vela cerró verde (posible amague).\n"
            "   👉 *Estrategia Day Trading*: Esperar confirmación para PUT, no arriesgar CALL."
        )
    else:
      if es_vela_verde:
        estrategia = (
            "📈 *Señal Alcista Confirmada*:\n"
            "   • Canal alcista activo y vela cerrada *Verde*.\n"
            "   👉 *Estrategia Day Trading*: Evitar PUT. *Oportunidad ideal para CALL* a"
            f" `${precio_actual}`."
        )
        senales_encontradas += 1
      else:
        estrategia = (
            "⚠️ *Atención Alcista*:\n"
            "   • Canal alcista pero la vela cerró roja (posible retroceso).\n"
            "   👉 *Estrategia Day Trading*: Precaución con los CALLs, vigilar soporte."
        )

    reporte_general += (
        f"📌 *{nombre}* ({hora_vela} NY):\n"
        f"   • Precio actual: `${precio_actual}`\n"
        f"   {estrategia}\n\n"
    )

  except Exception as e:
    continue

# Enviamos el reporte automatizado con las recomendaciones integradas
enviar_alerta_telegram(reporte_general)

print(
    f"\n✅ Análisis completado, Franz. Señales de Day Trading procesadas y"
    f" enviadas: {senales_encontradas}"
)
print("==========================================================================")